export type Confidence = "CONFIRMED" | "REPORTED" | "CLAIM" | "DELTA" | "HOLD";
export type SourceClass = "STATE" | "PRESS" | "MIL CLAIM" | "UN FFM" | "OPEN COMP";
export type Priority = "PRI-1" | "PRI-2" | "PRI-3";

export type TheaterId =
  | "overview"
  | "iran"
  | "levant"
  | "ukraine"
  | "sudan"
  | "energy"
  | "afpak";

export interface Kpi {
  label: string;
  value: string;
  tone: "hot" | "warn" | "ok" | "dim";
}

export interface EventItem {
  id: string;
  dtg: string;
  location: string;
  fact: string;
  source: SourceClass;
  confidence: Confidence;
  priority: Priority;
  lat: number;
  lon: number;
}

export interface Marker {
  id: string;
  name: string;
  lat: number;
  lon: number;
  note: string;
  tone: "hot" | "warn" | "ok" | "dim";
}

export interface Theater {
  id: TheaterId;
  name: string;
  short: string;
  status: string;
  pip: "hot" | "warn" | "ok" | "dim";
  map: { lat: number; lon: number; zoom: number };
  kpis: Kpi[];
  watch: string[];
  events: EventItem[];
  markers: Marker[];
}

export const SNAPSHOT = {
  dtgLocal: "2026-09-24 0915L",
  dtgZulu: "2026-09-24 1315Z",
  classification: "UNCLASSIFIED // OSINT // OPEN PRESS",
  watchcon: "ELEVATED",
  priorityTheater: "IRAN / GULF",
  sourceAge: "SNAPSHOT 24 SEP 2026 ~09:15 ET",
  disclaimer:
    "Best-effort open-source COP. Yellow = unverified claim. Dashed arcs are reconstructed from named origin+impact, not radar. Not a targeting product.",
};

export const THEATERS: Theater[] = [
  {
    id: "overview",
    name: "OVERVIEW",
    short: "GLOBAL",
    status: "IRAN CENTER OF GRAVITY",
    pip: "hot",
    map: { lat: 24.5, lon: 42, zoom: 3 },
    kpis: [
      { label: "PRIORITY THEATER", value: "IRAN / GULF", tone: "hot" },
      { label: "HORMUZ", value: "TANKER HIT", tone: "hot" },
      { label: "RIYADH AIR", value: "ALERT", tone: "warn" },
      { label: "UKRAINE WINDOW", value: "CITY / FUEL / ORF", tone: "hot" },
    ],
    watch: [
      "Does the US actually resume strikes on Iran?",
      "Hormuz AIS vs CENTCOM \u201copen\u201d language — UKMTO 141-26 debris strike",
      "Second Houthi shot at KSA energy / Riyadh",
      "Moscow ORF damage assessment / UA long-range cycle",
      "Kohat mosque attack + Pak\u2013Taliban escalation language (no confirmed new airstrike)",
      "Qatar channel: conditions vs talks",
    ],
    events: [
      {
        id: "ov-daraa",
        dtg: "21 SEP",
        location: "DARAA / YARMOUK",
        fact: "IDF artillery + MG fire on Wadi Abidin, Wadi al-Raqqad, outskirts of Jamla (Yarmouk Basin), western Daraa. Tip via IRNA Telegram; Anadolu/SANA/ANHA same. No casualties reported.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 32.67,
        lon: 35.88,
      },
            {
        id: "ov-ua-1",
        dtg: "20 SEP",
        location: "MOSCOW",
        fact: "UA mass drone wave; Moscow ORF Kapotnya hit; Sobyanin claims 1600+ drones / 450 toward Moscow; 2 dead Moscow region (Reuters).",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.75,
        lon: 37.62,
      },
      {
        id: "ov-af-1",
        dtg: "18\u201319 SEP",
        location: "KOHAT",
        fact: "Suicide VBIED + assault on Police Lines mosque (KP); 20+ dead. Pakistan says attackers had Afghan roots / TTP; Taliban deny. Sanctuary link CLAIM pending stronger corroboration.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.59,
        lon: 71.44,
      },
      {
        id: "ov-af-2",
        dtg: "20 SEP",
        location: "ISLAMABAD / KABUL",
        fact: "Islamabad: hit terrorists wherever they are. Taliban: crushing response IF Pakistan strikes; ask Saudi mediation. Statements REPORTED \u2014 no confirmed new Pak airstrike into Afghanistan 20\u201321 Sep.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.68,
        lon: 73.04,
      },
{
        id: "ov-1",
        dtg: "20 SEP",
        location: "TEHRAN",
        fact: "State media: military command claims intel the US, with some regional backing, is preparing to resume strikes. Threat: sustained hits on US bases; helpers treated as parties.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-1",
        lat: 35.69,
        lon: 51.39,
      },
      {
        id: "ov-2",
        dtg: "20 SEP",
        location: "RIYADH",
        fact: "Houthi missile toward Riyadh intercepted \u2014 first air-raid alert there this round. Ankara backs Saudi security.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.71,
        lon: 46.68,
      },
      {
        id: "ov-kkia",
        dtg: "19\u201321 SEP",
        location: "RIYADH KKIA",
        fact: "Press: Houthi strike on King Khalid Airport fuel storage / jet-fuel tanks; flights disrupted. Telegram satellite (Merrux) circles a tank farm \u2014 oval BDA is CLAIM, not a damage assessment.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.958,
        lon: 46.699,
      },
      {
        id: "ov-erbil",
        dtg: "20 SEP",
        location: "ERBIL",
        fact: "Hebrew Telegram: UAV hit near US consulate in Erbil. Greek press same cycle: drone downed near Erbil airport / coalition presence. Plume still is not a geolocation. City pin only \u2014 consulate vs airport is DELTA.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 36.191,
        lon: 44.009,
      },
      {
        id: "ov-3",
        dtg: "16 SEP",
        location: "HORMUZ",
        fact: "US military says the strait was kept open; tracking/press put shipping at new lows. Claims do not match.",
        source: "MIL CLAIM",
        confidence: "DELTA",
        priority: "PRI-2",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ov-taiz",
        dtg: "21 SEP",
        location: "TAIZ",
        fact: "Houthi-aligned Telegram (@sarzaminkhanjarha): Saudi strike on a local market in Taiz. Clip shows outdoor crowd/vehicles/tents then a fireball; “cmera 01” overlay. Does not prove Saudi, a market, or a specific site. City pin only — no market geolocation.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 13.58,
        lon: 44.02,
      },
      {
        id: "ov-madaribah",
        dtg: "21 SEP",
        location: "AL-MADARIBAH",
        fact: "Hebrew Telegram (Hananel Aviv): Southern Giants claim UAV hits on Houthi cells and military pickups on the Al-Wazia–Al-Madaribah front, west Lahij near Bab al-Mandeb. No strike geolocation. District pin only — not a pickup, not a control-line. Arab News 20 Sep has related fighting / a drone downed near Kahboub Mountain in the same district; that is the district fight, not this clip.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 12.72,
        lon: 43.9,
      },
      {
        id: "ov-7",
        dtg: "21 SEP",
        location: "HORMUZ",
        fact: "UKMTO 141-26: LPG tanker outbound Hormuz hit by debris from unknown projectiles. Crew safe, no spill. Press split inbound/oil/2 injured.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ov-8",
        dtg: "21 SEP",
        location: "ZVIAHEL",
        fact: "Zhytomyr OVA / Ukrinform: Russian strike on a gas station on M-06 near Zviahel. Twice this morning.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 50.59,
        lon: 27.61,
      },
      {
        id: "ov-9",
        dtg: "21 SEP",
        location: "ZAPORIZHZHIA",
        fact: "Ukrainian officials / Zelenskyy: drones hit a shopping center and Zaporizhzhia National University’s oldest building. Odesa: SES/OVA warehouse fires (chain name unconfirmed).",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 47.84,
        lon: 35.14,
      },
      {
        id: "ov-4",
        dtg: "20 SEP",
        location: "WEST BANK",
        fact: "Yom Kippur Eve shooting near Neve Tzuf/Halamish. Israeli man in his 30s critically wounded.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 32.04,
        lon: 35.12,
      },
      {
        id: "ov-5",
        dtg: "20 SEP",
        location: "KYIV",
        fact: "Witkoff still talking a \u201cgood resolution\u201d after Kyiv; pushing trilateral talks. No deal text.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-3",
        lat: 50.45,
        lon: 30.52,
      },
      {
        id: "ov-6",
        dtg: "20 SEP",
        location: "KORDOFAN",
        fact: "No last-4h break. SAF claiming North Kordofan gains vs RSF; fighting reported near the Ethiopia border.",
        source: "PRESS",
        confidence: "HOLD",
        priority: "PRI-3",
        lat: 14.4,
        lon: 29.5,
      },
    ],
    markers: [
      { id: "m-iran", name: "IRAN / GULF", lat: 27.1, lon: 56.3, note: "Strike-cycle watch", tone: "hot" },
      { id: "m-riyadh", name: "RIYADH", lat: 24.71, lon: 46.68, note: "Air-raid intercept", tone: "warn" },
      { id: "m-kkia", name: "KKIA FUEL", lat: 24.958, lon: 46.699, note: "Fuel tanks 19\u201320 Sep", tone: "hot" },
      { id: "m-wb", name: "WEST BANK", lat: 32.0, lon: 35.2, note: "Active incidents", tone: "warn" },
      { id: "m-ukr", name: "UKRAINE", lat: 48.4, lon: 35.0, note: "Moscow drone wave", tone: "hot" },
      { id: "m-kohat", name: "KOHAT / AFPAK", lat: 33.59, lon: 71.44, note: "Mosque attack + escalation talk", tone: "warn" },
      { id: "m-sud", name: "SUDAN", lat: 15.5, lon: 32.5, note: "SAF / RSF", tone: "hot" },
      { id: "m-taiz", name: "TAIZ", lat: 13.58, lon: 44.02, note: "Market-strike CLAIM", tone: "warn" },
      { id: "m-madaribah", name: "AL-MADARIBAH", lat: 12.72, lon: 43.9, note: "Giants UAV CLAIM", tone: "warn" },
      { id: "m-erbil", name: "ERBIL", lat: 36.191, lon: 44.009, note: "UAV CLAIM 20 Sep", tone: "warn" },
    ],
  },
  {
    id: "iran",
    name: "IRAN / GULF",
    short: "GULF",
    status: "RE-STRIKE WATCH",
    pip: "hot",
    map: { lat: 26.6, lon: 55.2, zoom: 6 },
    kpis: [
      { label: "CONFLICT CLOCK", value: "D+204", tone: "hot" },
      { label: "HORMUZ", value: "BLOCK / ESCORT", tone: "warn" },
      { label: "DIPLO", value: "QATAR CHANNEL", tone: "warn" },
      { label: "NEXT MOVE", value: "RE-STRIKE WATCH", tone: "hot" },
    ],
    watch: [
      "US resume-strikes claim vs actual sortie generation",
      "Qeshm / Bandar Abbas follow-on hits",
      "IRGC boardings / mines vs US escort narrative",
      "Qatar-passed conditions to Washington",
    ],
    events: [
            {
        id: "ir-trend",
        dtg: "18 SEP",
        location: "HORMUZ",
        fact: "IRGC claim: tanker Trend detained in Hormuz. Confidence CLAIM only \u2014 state narrative, not independently confirmed.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 26.57,
        lon: 56.25,
      },
{
        id: "ir-1",
        dtg: "20 SEP",
        location: "TEHRAN",
        fact: "Tehran (state): intel that the US, with some regional backing, is prepping to resume strikes.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-1",
        lat: 35.69,
        lon: 51.39,
      },
      {
        id: "ir-2",
        dtg: "20 SEP",
        location: "TEHRAN",
        fact: "Ghalibaf: \u201cdevastating blows\u201d first, talks later. SNSC Rezaei: conditions already sent to Washington via Qatar.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-1",
        lat: 35.7,
        lon: 51.4,
      },
      {
        id: "ir-3",
        dtg: "16 SEP",
        location: "HORMUZ",
        fact: "US military: Hormuz \u201ckept open.\u201d Tracking / press: shipping at new lows.",
        source: "MIL CLAIM",
        confidence: "DELTA",
        priority: "PRI-2",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ir-7",
        dtg: "21 SEP",
        location: "HORMUZ",
        fact: "UKMTO 141-26 ATTACK, 1330Z: LPG tanker outbound Hormuz hit by debris from unknown projectiles. Crew safe, no spill, proceeding. Press split inbound/oil/2 injured.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ir-erbil",
        dtg: "20 SEP",
        location: "ERBIL",
        fact: "Hebrew Telegram (News_il_h): UAV near US consulate, Erbil. Same-day Greek press: drone downed near Erbil airport / coalition presence; Reuters/AFP cited on intercept. Smoke still is not a site geolocation. City pin \u2014 consulate vs airport DELTA.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 36.191,
        lon: 44.009,
      },
      {
        id: "ir-4",
        dtg: "13 SEP",
        location: "QESHM",
        fact: "Iranian cargo struck off Qeshm. State media: 1 killed, 4 wounded. Neighbor brief postponed.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.76,
        lon: 55.8,
      },
      {
        id: "ir-5",
        dtg: "08 SEP",
        location: "BANDAR ABBAS",
        fact: "Iran: MQ-1 Predator downed over Bandar Abbas. IRGC: seized US-made Dive-LD UUV at Hormuz entrance.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 27.18,
        lon: 56.27,
      },
      {
        id: "ir-6",
        dtg: "28 FEB",
        location: "HORMUZ",
        fact: "US\u2013Israel air war opens. IRGC moves to choke Hormuz. Pre-war: ~25% seaborne oil / ~20% LNG.",
        source: "OPEN COMP",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 26.6,
        lon: 56.3,
      },
    ],
    markers: [
      { id: "hormuz", name: "HORMUZ", lat: 26.57, lon: 56.25, note: "UKMTO 141-26 debris strike 21 Sep", tone: "hot" },
      { id: "qeshm", name: "QESHM", lat: 26.76, lon: 55.8, note: "Cargo strike 13 Sep", tone: "warn" },
      { id: "babb", name: "BANDAR ABBAS", lat: 27.18, lon: 56.27, note: "UAS / UUV claims", tone: "warn" },
      { id: "tehran", name: "TEHRAN", lat: 35.69, lon: 51.39, note: "Resume-strike messaging", tone: "hot" },
      { id: "erbil", name: "ERBIL", lat: 36.191, lon: 44.009, note: "UAV CLAIM 20 Sep", tone: "warn" },
    ],
  },
  {
    id: "levant",
    name: "LEVANT",
    short: "LEVANT",
    status: "WB ACTIVE / LEB OCC",
    pip: "warn",
    map: { lat: 32.6, lon: 35.4, zoom: 7 },
    kpis: [
      { label: "LEBANON", value: "CEASEFIRE / OCC", tone: "warn" },
      { label: "WEST BANK", value: "ACTIVE", tone: "hot" },
      { label: "GAZA", value: "YELLOW LINE", tone: "dim" },
      { label: "HOUTHI\u2013KSA", value: "AIR RAID", tone: "warn" },
    ],
    watch: [
      "Yellow Line crossings in Gaza",
      "South Lebanon occupation incidents",
      "West Bank outpost / shooting cycle",
      "Houthi follow-on vs Riyadh / energy",
      "Taiz market-strike CLAIM — city pin only, no site geolocation",
      "Al-Madaribah Giants UAV CLAIM — district pin only, no pickup geolocation",
      "IDF activity Daraa/Quneitra buffer",
    ],
    events: [
      {
        id: "lv-mansouri",
        dtg: "21 SEP",
        location: "MANSOURI / DEIR SIRYAN",
        fact: "Telegram (301 Arab World): smoke plumes over Deir Siryan and al-Mansouri, south Lebanon. Stills show distant white columns only — no munition ID. Press already had IDF fire on Mansouri; this clip is CLAIM for these two towns.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 33.178,
        lon: 35.214,
      },
      {
        id: "lv-burqin",
        dtg: "21 SEP",
        location: "BURQIN",
        fact: "Telegram (301 Arab World): clashes in Burqin, Jenin — stones thrown at Israeli forces. Clip not independently corroborated here.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-3",
        lat: 32.456,
        lon: 35.26,
      },
      {
        id: "lv-silwan",
        dtg: "21 SEP",
        location: "SILWAN",
        fact: "Telegram (301 Arab World): clashes in Silwan now. Clip not independently corroborated here.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-3",
        lat: 31.77,
        lon: 35.237,
      },
      {
        id: "lv-tuffah",
        dtg: "21 SEP",
        location: "GAZA / TUFFAH",
        fact: "Telegram (301 Arab World): UAV strike in Tuffah, east Gaza City; one killed. Press TV same neighborhood: warplanes hit a residential building. Collage (night plume + later rubble) is not a building geolocation. Neighborhood pin only.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.506,
        lon: 34.466,
      },
      {
        id: "lv-shujaiyya",
        dtg: "21 SEP",
        location: "SHUJA'IYYA",
        fact: "Hebrew Telegram (@ramreports): strike on a ‘terror target’ behind the courthouse mosque, east of Shuja'iyya junction, east Gaza City. Night plume is not a geolocation. Neighborhood pin only — not the mosque.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.501,
        lon: 34.468,
      },
      {
        id: "lv-khanyounis",
        dtg: "21 SEP",
        location: "KHAN YOUNIS",
        fact: "Militant Telegram: IDF demolition in southern Khan Younis. Caption-only, no clip geolocation this pass. City-south pin — not a building.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.344,
        lon: 34.303,
      },
      {
        id: "lv-taiz",
        dtg: "21 SEP",
        location: "TAIZ",
        fact: "Houthi-aligned Telegram (@sarzaminkhanjarha): Saudi strike on a local market in Taiz. Clip: outdoor gathering + fireball, camera overlay. Unverified attribution/site. City pin only — no market geolocation.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 13.58,
        lon: 44.02,
      },
      {
        id: "lv-madaribah",
        dtg: "21 SEP",
        location: "AL-MADARIBAH",
        fact: "Hebrew Telegram (Hananel Aviv): Southern Giants claim UAV hits on Houthi cells and military pickups on the Al-Wazia–Al-Madaribah front, west Lahij near Bab al-Mandeb. Clip not independently geolocated. District pin only — not a vehicle, not a control-line. Arab News 20 Sep: Nation’s Shield / Giants fighting and a drone downed near Kahboub Mountain in Al-Madaribah Wa Al-Aarah — related district fight, not this clip.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 12.72,
        lon: 43.9,
      },
      {
        id: "lv-6",
        dtg: "21 SEP",
        location: "DARAA / YARMOUK",
        fact: "IDF artillery + MG fire on Wadi Abidin, Wadi al-Raqqad, outskirts of Jamla (Yarmouk Basin), western Daraa. Tip via IRNA Telegram; Anadolu/SANA/ANHA same. No casualties reported.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 32.67,
        lon: 35.88,
      },
      {
        id: "lv-1",
        dtg: "20 SEP",
        location: "RIYADH",
        fact: "Houthi missile toward Riyadh intercepted. Riyadh hosting Red Sea shipping-protection naval meeting.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.71,
        lon: 46.68,
      },
      {
        id: "lv-kkia",
        dtg: "19\u201321 SEP",
        location: "RIYADH KKIA",
        fact: "Press: Houthi strike on King Khalid Airport jet-fuel tanks; flights disrupted. Telegram satellite (Merrux) circles a tank farm \u2014 oval BDA is CLAIM, not a damage assessment.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.958,
        lon: 46.699,
      },
      {
        id: "lv-2",
        dtg: "20 SEP",
        location: "NEVE TZU",
        fact: "Yom Kippur Eve shooting at a spring near Neve Tzuf/Halamish. Shooter later detained after a hospital raid.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 32.04,
        lon: 35.12,
      },
      {
        id: "lv-3",
        dtg: "20 SEP",
        location: "JENIN",
        fact: "IDF killed a Palestinian near new Ganim outpost; claimed ramming attempt.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 32.46,
        lon: 35.3,
      },
      {
        id: "lv-4",
        dtg: "PRIOR",
        location: "GAZA",
        fact: "IDF reported killing 2 in the north after a Yellow Line crossing. Katz prior: energy-infra strike threat if Iran hits Israel.",
        source: "MIL CLAIM",
        confidence: "HOLD",
        priority: "PRI-3",
        lat: 31.5,
        lon: 34.47,
      },
      {
        id: "lv-5",
        dtg: "20 SEP",
        location: "ALEPPO",
        fact: "OSINT account @IntelSlava: ammunition depot exploded in Aleppo; multiple secondary explosions seen and heard nearby. War Map Live cites SOHR near Ikarda (aggregator; SOHR page not reviewed). Single-source tip + second signal; city pin only \u2014 no depot geolocation.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 36.2,
        lon: 37.16,
      },
    ],
    markers: [
      { id: "kkia", name: "KKIA FUEL", lat: 24.958, lon: 46.699, note: "Jet-fuel tanks 19\u201320 Sep", tone: "hot" },
      { id: "sleb", name: "SOUTH LEBANON", lat: 33.2, lon: 35.3, note: "Occupation / Litani", tone: "warn" },
      { id: "mansouri", name: "MANSOURI", lat: 33.178, lon: 35.214, note: "Smoke CLAIM 21 Sep", tone: "warn" },
      { id: "deir-siryan", name: "DEIR SIRYAN", lat: 33.283, lon: 35.533, note: "Smoke CLAIM 21 Sep", tone: "warn" },
      { id: "jenin", name: "JENIN / GANIM", lat: 32.46, lon: 35.3, note: "Outpost incident", tone: "hot" },
      { id: "burqin", name: "BURQIN", lat: 32.456, lon: 35.26, note: "Clashes CLAIM", tone: "warn" },
      { id: "gaza", name: "GAZA", lat: 31.5, lon: 34.47, note: "Yellow Line", tone: "dim" },
      { id: "khan-younis", name: "KHAN YOUNIS", lat: 31.344, lon: 34.303, note: "Demolition CLAIM", tone: "warn" },
      { id: "tuffah", name: "TUFFAH", lat: 31.506, lon: 34.466, note: "UAV CLAIM 21 Sep", tone: "hot" },
      { id: "shujaiyya", name: "SHUJA'IYYA", lat: 31.501, lon: 34.468, note: "Strike CLAIM 21 Sep", tone: "warn" },
      { id: "halamish", name: "HALAMISH", lat: 32.04, lon: 35.12, note: "Shooting", tone: "hot" },
      { id: "silwan", name: "SILWAN", lat: 31.77, lon: 35.237, note: "Clashes CLAIM", tone: "warn" },
      { id: "aleppo", name: "ALEPPO", lat: 36.2, lon: 37.16, note: "Ammo depot claim", tone: "warn" },
      { id: "daraa-yarmouk", name: "DARAA / YARMOUK", lat: 32.67, lon: 35.88, note: "IDF shelling 21 Sep", tone: "warn" },
      { id: "taiz", name: "TAIZ", lat: 13.58, lon: 44.02, note: "Market-strike CLAIM 21 Sep", tone: "warn" },
      { id: "madaribah", name: "AL-MADARIBAH", lat: 12.72, lon: 43.9, note: "Giants UAV CLAIM 21 Sep", tone: "warn" },
    ],
  },
  {
    id: "ukraine",
    name: "UKRAINE",
    short: "UKR",
    status: "ORF + CITY / FUEL",
    pip: "hot",
    map: { lat: 50.5, lon: 35.5, zoom: 5.5 },
    kpis: [
      { label: "CLOCK", value: "D+1671", tone: "dim" },
      { label: "ENERGY STRIKE", value: "MOSCOW ORF", tone: "hot" },
      { label: "DIPLO", value: "WITKOFF", tone: "dim" },
      { label: "LAST 4H", value: "FUEL / CITY", tone: "hot" },
    ],
    watch: [
      "Moscow ORF damage assessment (AVT-6 / processing / isomerization)",
      "Russian election-day narrative vs UA long-range campaign",
      "Winter energy-grid strike cycle — Zviahel fuel + Odesa warehouses",
      "Witkoff trilateral — still no text",
      "Pokrovsk / Donbas as HOLD",
    ],
    events: [
            {
        id: "uk-kap",
        dtg: "20 SEP",
        location: "KAPOTNYA",
        fact: "Gazprom Neft Moscow ORF hit (AVT-6 etc); Zelensky/Gen Staff confirm; Reuters: 2 dead Moscow region.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.635,
        lon: 37.795,
      },
      {
        id: "uk-wave",
        dtg: "20 SEP",
        location: "MOSCOW",
        fact: "Sobyanin: largest drone attack; 1600+ downed claim / 450 toward Moscow.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.75,
        lon: 37.62,
      },
{
        id: "uk-1",
        dtg: "20 SEP",
        location: "KYIV",
        fact: "Witkoff still talking a \u201cgood resolution\u201d after Kyiv; pushing trilateral talks. No deal text.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-3",
        lat: 50.45,
        lon: 30.52,
      },
      {
        id: "uk-2",
        dtg: "20 SEP",
        location: "WARSAW",
        fact: "Tusk: Moscow will not talk without Ukraine\u2019s \u201ctotal capitulation\u201d; winter to be made \u201ctragically critical.\u201d",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-3",
        lat: 52.23,
        lon: 21.01,
      },
      {
        id: "uk-3",
        dtg: "20 SEP",
        location: "DONBAS",
        fact: "Kyiv denounces Russian Duma vote being run in illegally annexed oblasts. Zelenskyy eastern-Europe huddle through Sunday.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-3",
        lat: 48.0,
        lon: 37.8,
      },
      {
        id: "uk-4",
        dtg: "21 SEP",
        location: "ZVIAHEL",
        fact: "Zhytomyr OVA / Ukrinform: Russian strike on a gas station on the M-06 Kyiv–Chop highway near Zviahel. Twice this morning; traffic restrictions later lifted.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 50.59,
        lon: 27.61,
      },
      {
        id: "uk-5",
        dtg: "21 SEP",
        location: "ZAPORIZHZHIA",
        fact: "Ukrainian officials / Zelenskyy: drones damaged a shopping center and Zaporizhzhia National University’s oldest building. Injury counts differ across press.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 47.84,
        lon: 35.14,
      },
      {
        id: "uk-6",
        dtg: "21 SEP",
        location: "ODESA",
        fact: "SES / Odesa OVA: warehouse fires after overnight strikes. Telegram named Silpo; officials said supermarket-chain warehouses, no casualties.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 46.48,
        lon: 30.73,
      },
      {
        id: "uk-7",
        dtg: "21 SEP",
        location: "KHARKIV",
        fact: "OSINT (@war_cube / JHArnous): geolocated strike on Epicentr, Kharkiv 49.908390, 36.275573. Stills show ISR reticle + blurred aftermath overlay. Site name not independently confirmed here.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 49.90839,
        lon: 36.275573,
      },
      {
        id: "uk-8",
        dtg: "21 SEP",
        location: "ODESA",
        fact: "OSINT (@war_cube / JHArnous): unknown warehouse hit at 46.524836, 30.602931. Aligns with SES/OVA warehouse-fire reporting; specific building is a geolocation CLAIM.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 46.524836,
        lon: 30.602931,
      },
      {
        id: "uk-9",
        dtg: "21 SEP",
        location: "NOVOALEKSANDROVKA",
        fact: "RV voenkor map: 128 OMSBr took Novoaleksandrovka (Vovchansk raion) from Ukraine’s 129th. Single-source MIL CLAIM — no independent confirmation in this pass. Village pin only, no control-line.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 50.15739,
        lon: 37.24777,
      },
      {
        id: "uk-10",
        dtg: "21 SEP",
        location: "POLNAYA",
        fact: "RV voenkor map: 82 MSP took Polnaya after 57th OMBr. Same single-source claim as Novoaleksandrovka. Village pin only.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 50.16157,
        lon: 36.98636,
      },
    ],
    markers: [
      { id: "kapotnya", name: "KAPOTNYA ORF", lat: 55.635, lon: 37.795, note: "ORF hit / fire", tone: "hot" },
      { id: "moscow", name: "MOSCOW", lat: 55.75, lon: 37.62, note: "Mass drone wave", tone: "hot" },
      { id: "kyiv", name: "KYIV", lat: 50.45, lon: 30.52, note: "Long-range / diplo", tone: "warn" },
      { id: "pokrovsk", name: "POKROVSK AXIS", lat: 48.28, lon: 37.18, note: "HOLD", tone: "warn" },
      { id: "blacksea", name: "BLACK SEA", lat: 45.3, lon: 32.5, note: "Energy / maritime", tone: "dim" },
      { id: "zviahel", name: "ZVIAHEL", lat: 50.59, lon: 27.61, note: "M-06 fuel strike 21 Sep", tone: "hot" },
      { id: "zaporizhzhia", name: "ZAPORIZHZHIA", lat: 47.84, lon: 35.14, note: "Mall / ZNU drones", tone: "warn" },
      { id: "odesa", name: "ODESA", lat: 46.48, lon: 30.73, note: "Warehouse fires (OVA)", tone: "warn" },
      { id: "kharkiv-epicentr", name: "KHARKIV EPICENTR", lat: 49.90839, lon: 36.275573, note: "OSINT geoloc CLAIM", tone: "warn" },
      { id: "odesa-wh", name: "ODESA WAREHOUSE", lat: 46.524836, lon: 30.602931, note: "OSINT geoloc CLAIM", tone: "warn" },
      { id: "novoaleks", name: "NOVOALEKSANDROVKA", lat: 50.15739, lon: 37.24777, note: "RV capture CLAIM", tone: "warn" },
      { id: "polnaya", name: "POLNAYA", lat: 50.16157, lon: 36.98636, note: "RV capture CLAIM", tone: "warn" },
    ],
  },
  {
    id: "sudan",
    name: "SUDAN",
    short: "SUDAN",
    status: "SAF / RSF HOLD",
    pip: "warn",
    map: { lat: 15.5, lon: 32.0, zoom: 5.5 },
    kpis: [
      { label: "WAR", value: "SAF vs RSF", tone: "hot" },
      { label: "DARFUR", value: "EL FASHER", tone: "warn" },
      { label: "KORDOFAN", value: "SAF CLAIMS", tone: "warn" },
      { label: "LAST 4H", value: "NO BREAK", tone: "ok" },
    ],
    watch: [
      "El Fasher / Zamzam humanitarian picture",
      "North Kordofan \u2014 verify SAF claims",
      "Ethiopia-border fighting",
      "External pipelines (UAE / Chad / Libya / Bosaso)",
    ],
    events: [
      {
        id: "sd-1",
        dtg: "20 SEP",
        location: "N. KORDOFAN",
        fact: "No material last-4h break. SAF still claiming North Kordofan gains vs RSF. Fighting reported near the Ethiopia border.",
        source: "PRESS",
        confidence: "HOLD",
        priority: "PRI-3",
        lat: 14.4,
        lon: 29.5,
      },
      {
        id: "sd-2",
        dtg: "07 SEP",
        location: "SUDAN",
        fact: "Control map refresh: SAF/TSC vs RSF \u201cGovernment of Peace and Unity\u201d vs SPLM-N (al-Hilu) mixed zones.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 15.5,
        lon: 32.5,
      },
      {
        id: "sd-3",
        dtg: "PRIOR",
        location: "EL FASHER",
        fact: "UN FFM: hallmarks of genocide at El-Fasher/Zamzam; up to ~2,000 former Colombian contractors with RSF; foreign drones both sides.",
        source: "UN FFM",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 13.63,
        lon: 25.35,
      },
    ],
    markers: [
      { id: "khartoum", name: "KHARTOUM", lat: 15.5, lon: 32.53, note: "Capital axis", tone: "dim" },
      { id: "elfasher", name: "EL FASHER", lat: 13.63, lon: 25.35, note: "UN FFM", tone: "hot" },
      { id: "kordofan", name: "N. KORDOFAN", lat: 14.4, lon: 29.5, note: "SAF claims", tone: "warn" },
    ],
  },
  {
    id: "energy",
    name: "ENERGY / SEA",
    short: "SEA",
    status: "HORMUZ TANKER HIT",
    pip: "hot",
    map: { lat: 22.4, lon: 48.2, zoom: 5 },
    kpis: [
      { label: "HORMUZ FLOW", value: "TANKER HIT", tone: "hot" },
      { label: "BRENT PEAK", value: "$126", tone: "warn" },
      { label: "RED SEA", value: "HOUTHI", tone: "warn" },
      { label: "ALT ROUTE", value: "PANAMA TIGHT", tone: "dim" },
    ],
    watch: [
      "AIS vs \u201copen strait\u201d language — UKMTO 141-26 debris strike",
      "Bab el-Mandeb / Red Sea meeting in Riyadh",
      "Al-Madaribah / west Lahij Giants UAV CLAIM — district only, Bab marker unchanged",
      "Moscow ORF / Kapotnya damage vs Russian refining",
      "Second-order: LNG, fertilizer, helium, aluminum",
      "Gulf/ME flight disruption / travel alerts",
    ],
    events: [
            {
        id: "en-4",
        dtg: "20 SEP",
        location: "KAPOTNYA",
        fact: "UA strike on Gazprom Neft Moscow Oil Refinery (energy infra); AVT-6 / processing units hit; large fire reported.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.635,
        lon: 37.795,
      },
{
        id: "en-1",
        dtg: "16 SEP",
        location: "HORMUZ",
        fact: "Competing claims: US says strait kept open; press says shipping at lowest level yet.",
        source: "PRESS",
        confidence: "DELTA",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "en-2",
        dtg: "21 APR",
        location: "PERSIAN GULF",
        fact: "IMO: about 20,000 mariners and 2,000 ships stranded in the Gulf at peak closure.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 27.0,
        lon: 51.0,
      },
      {
        id: "en-3",
        dtg: "20 SEP",
        location: "RIYADH",
        fact: "Red Sea shipping-protection naval meeting hosted in Riyadh after Houthi intercept.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.71,
        lon: 46.68,
      },
      {
        id: "en-kkia",
        dtg: "19\u201321 SEP",
        location: "RIYADH KKIA",
        fact: "Press: Houthi strike on King Khalid Airport fuel storage / jet-fuel tanks. Telegram satellite oval is CLAIM BDA, not independent confirmation of which tanks burned.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.958,
        lon: 46.699,
      },
      {
        id: "en-5",
        dtg: "21 SEP",
        location: "HORMUZ",
        fact: "UKMTO 141-26: LPG tanker outbound Hormuz hit by debris from unknown projectiles. Crew safe, no environmental impact. Press split inbound vs outbound, LPG vs oil, 0 vs 2 injured.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
    ],
    markers: [
      { id: "kapotnya-en", name: "KAPOTNYA ORF", lat: 55.635, lon: 37.795, note: "UA ORF strike", tone: "hot" },
      { id: "kkia-en", name: "KKIA FUEL", lat: 24.958, lon: 46.699, note: "Jet-fuel tanks 19\u201320 Sep", tone: "hot" },
      { id: "hormuz2", name: "HORMUZ", lat: 26.57, lon: 56.25, note: "UKMTO 141-26 debris strike 21 Sep", tone: "hot" },
      { id: "bab", name: "BAB EL-MANDEB", lat: 12.58, lon: 43.33, note: "Houthi / Red Sea", tone: "warn" },
      { id: "suez", name: "SUEZ", lat: 30.0, lon: 32.55, note: "Alt artery", tone: "dim" },
    ],
  },
  {
    id: "afpak",
    name: "AFPAK",
    short: "AFPAK",
    status: "KOHAT / ESCALATION TALK",
    pip: "warn",
    map: { lat: 33.5, lon: 70.5, zoom: 6 },
    kpis: [
      { label: "KOHAT", value: "MOSQUE ATTACK", tone: "hot" },
      { label: "PAK LINE", value: "HIT WHEREVER", tone: "warn" },
      { label: "TALIBAN", value: "CRUSHING IF STRUCK", tone: "warn" },
      { label: "NEW AIRSTRIKE", value: "NOT CONFIRMED", tone: "ok" },
    ],
    watch: [
      "Any confirmed Pakistan cross-border strike (none named 20\u201321 Sep)",
      "Kohat investigation \u2014 Afghan-roots / TTP claim vs Taliban denial",
      "Saudi mediation channel",
      "Feb\u2013Mar 2026 strike cycle remains PRIOR reference only",
    ],
    events: [
      {
        id: "af-1",
        dtg: "18\u201319 SEP",
        location: "KOHAT",
        fact: "Suicide VBIED + assault on Police Lines mosque; 20+ dead. Pakistan links attackers to Afghanistan / TTP (CLAIM on sanctuary until stronger corroboration).",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 33.59,
        lon: 71.44,
      },
      {
        id: "af-2",
        dtg: "20 SEP",
        location: "ISLAMABAD",
        fact: "Pakistan warns it will hit terrorists wherever they are. Statement REPORTED \u2014 not an airstrike report.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.68,
        lon: 73.04,
      },
      {
        id: "af-3",
        dtg: "20 SEP",
        location: "KABUL",
        fact: "Taliban warn crushing response IF Pakistan strikes; ask Saudi mediation. Statement REPORTED.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 34.53,
        lon: 69.17,
      },
      {
        id: "af-4",
        dtg: "PRIOR",
        location: "AFGHANISTAN",
        fact: "Last major named Pakistan cross-border strike cycle: Feb\u2013Mar 2026 (Kabul/Kandahar/Nangarhar etc.). No reconstructed vector this refresh \u2014 need named origin+impact pairs.",
        source: "PRESS",
        confidence: "HOLD",
        priority: "PRI-3",
        lat: 34.53,
        lon: 69.17,
      },
    ],
    markers: [
      { id: "kohat", name: "KOHAT", lat: 33.59, lon: 71.44, note: "Police Lines mosque attack", tone: "hot" },
      { id: "islamabad", name: "ISLAMABAD", lat: 33.68, lon: 73.04, note: "Hit-wherever language", tone: "warn" },
      { id: "kabul", name: "KABUL", lat: 34.53, lon: 69.17, note: "Crushing-if-struck warning", tone: "warn" },
    ],
  },
];

export const TICKER = THEATERS[0].events.map(
  (e) => `${e.dtg}  ${e.location}  ${e.fact}`,
);
