import type { Theater } from "./sitrep.types";

export const THEATER_UKRAINE: Theater =   {
    id: "ukraine",
    name: "UKRAINE",
    short: "UKR",
    status: "MASS STRIKE / BLACK SEA SHIPS",
    pip: "hot",
    map: { lat: 50.5, lon: 35.5, zoom: 5.5 },
    kpis: [
      { label: "CLOCK", value: "D+1687", tone: "dim" },
      { label: "ENERGY STRIKE", value: "VOLGOGRAD HALT", tone: "hot" },
      { label: "DIPLO", value: "STALLED", tone: "warn" },
      { label: "LATEST", value: "07 OCT MASS STRIKE", tone: "hot" },
    ],
    watch: [
      "Pryluky toll / 7 Oct grid damage assessment",
      "Bridge-strike campaign: Kyiv \u2192 Zaporizhzhia; Chonhar collapse",
      "W. Black Sea ship attacks \u2014 attribution (Bulgaria / Romania)",
      "Ukrainian refinery campaign: Volgograd halt, Moscow fuel hub",
      "Operation Vivaldi gains vs RU push south of Dobropillya (ISW)",
      "Pokrovsk / Donbas as HOLD",
    ],
    events: [
      {
        id: "uk-0710",
        dtg: "07 OCT",
        location: "PRYLUKY / NATIONWIDE",
        fact: "Ukr Air Force (Al Jazeera): overnight 130 drones, 48 cruise missiles plus ballistic missiles; 161 targets downed. Zelenskyy: ~70 missiles, energy a key target. Kyiv Independent (Ukr officials): cruise missile hit a 5-storey residential block in Pryluky (Chernihiv Obl.) \u2014 at least 19 killed incl. 5 children, 55 injured (earlier AJ count 14); Kyiv Darnytskyi district 3 killed, 8 injured (Klitschko); deaths also in Kremenchuk and Kirovohrad Obl.; KI: 30+ killed, 138 injured in 24h. RU MoD: \u201cmassive strike\u201d on military-industrial sites incl. Fire Point Flamingo production. Pryluky city pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 50.595,
        lon: 32.387,
      },
      {
        id: "uk-blacksea",
        dtg: "05\u201306 OCT",
        location: "W. BLACK SEA",
        fact: "Bulgarian PM Radev (Reuters): air and sea drones hit two merchant ships ~70 nm east of Byala in Bulgaria\u2019s EEZ; Togo-flagged ALFA WATAN sank, crew missing (search ended 7 Oct, Al Jazeera); Palau-flagged ABLE hit, 2 injured. Radev unsure of the drones\u2019 origin; Zelenskyy says Russia; Moscow no comment. Romanian MoI (via ISW): 5 Oct vessel fire ~30 nm south of Sfantu Gheorghe, 2 dead, ship sank. Erdogan\u2013Putin call on Black Sea safety (Al Jazeera). Black Sea area pin only \u2014 not the incident positions.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 45.3,
        lon: 32.5,
      },
      {
        id: "uk-zp-bridge",
        dtg: "06 OCT",
        location: "ZAPORIZHZHIA",
        fact: "Zaporizhzhia OVA head Semikin (via ISW): Russian strike hit a bridge over the Dnipro in Zaporizhzhia city; ISW notes Russia\u2019s intensified bridge strikes, incl. Kyiv. OSINT satellite imagery (via ISW): Chonhar bridge collapsed (26/30 Sep). City pin.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 47.84,
        lon: 35.14,
      },
      {
        id: "uk-moscow-fuel",
        dtg: "05\u201306 OCT",
        location: "MOSCOW REGION",
        fact: "Reuters factbox (citing Russian milbloggers): Ukrainian drones hit a major fuel hub in Moscow region, 2 killed. ISW: geolocated footage of a large fire at the Volodarskaya pumping station (Konstantinovo); Gov. Vorobyov said the oblast was struck. Region pin only.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.75,
        lon: 37.62,
      },
      {
        id: "uk-volgograd",
        dtg: "02 OCT",
        location: "VOLGOGRAD",
        fact: "Reuters (two industry sources): Lukoil Volgograd refinery fully halted crude processing after drone damage. Novoshakhtinsk refinery suspended operations after attack (governor, 25 Sep). Ukr MoD (via ISW) claims >51% of Russian refining capacity disabled \u2014 CLAIM. City pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 48.708,
        lon: 44.515,
      },
      {
        id: "uk-kyiv-0928",
        dtg: "28 SEP",
        location: "KYIV",
        fact: "AP: Russian drones hit the National Academy of Sciences building in central Kyiv, killing a woman; 4 killed in Kyiv region; Dnipro office centre hit, 3 killed, 18 wounded; Kharkiv apartment block, 43 wounded. Peskov: Ukraine \u201cwill have to pay a price.\u201d City pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 50.45,
        lon: 30.52,
      },
      {
        id: "uk-lyman",
        dtg: "28 SEP\u201306 OCT",
        location: "LYMAN AXIS",
        fact: "Ukraine\u2019s 3rd Army Corps (AP, 28 Sep) claims 176 km\u00b2 retaken under Operation Vivaldi \u2014 CLAIM. ISW 6 Oct assesses recent Ukrainian gains north/northeast of Lyman and east of Orikhiv; Russia\u2019s highest tempo is south of Dobropillya. RU MoD claims Novovodiane and Ulanove (AP: unverified); ISW does not support the Holubkove claim. Town pin \u2014 no line positions.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 48.98,
        lon: 37.817,
      },
      {
        id: "uk-kyiv-24",
        dtg: "24 SEP",
        location: "KYIV",
        fact: "Overnight RU missiles/drones: Zelenskyy/Klitschko \u2014 Kyiv ballistic + drones; 2 dead capital; maternity-hospital area/residential/energy/logistics damaged (France24/AFP, RFE/RL). Ukr AF: Zircon, Iskander, 282 drones mainly Kyiv/Odesa. City pin only.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 50.45,
        lon: 30.52,
      },
      {
        id: "uk-chuhuiv",
        dtg: "24 SEP",
        location: "CHUHUIV DIST.",
        fact: "PM Koretsky: RU strike on farm in Chuhuiv district (SE Kharkiv) killed 6 at vegetable storage (France24/AFP). District named; pin is Chuhuiv seat only \u2014 not a warehouse geolocation.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 49.84,
        lon: 36.68,
      },
      {
        id: "uk-lavrov",
        dtg: "23 SEP",
        location: "NEW YORK",
        fact: "AP: Lavrov tells UN channel Moscow is open to talks but will not accept a break in hostilities before a peace deal. Met Rubio on UNGA sidelines; Rubio says Trump invited Putin to December G20 in Miami.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 40.75,
        lon: -73.97,
      },
      {
        id: "uk-kap",
        dtg: "20 SEP",
        location: "KAPOTNYA",
        fact: "Gazprom Neft Moscow ORF hit (AVT-6 etc); Zelensky/Gen Staff confirm; Reuters: 2 dead Moscow region.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.635,
        lon: 37.795,
      },
      {
        id: "uk-wave",
        dtg: "20 SEP",
        location: "MOSCOW",
        fact: "Sobyanin: largest drone attack; 1600+ downed claim / 450 toward Moscow.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.75,
        lon: 37.62,
      },
      {
        id: "uk-6",
        dtg: "21 SEP",
        location: "ODESA",
        fact: "SES / Odesa OVA: warehouse fires after overnight strikes. Telegram named Silpo; officials said supermarket-chain warehouses, no casualties.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 46.48,
        lon: 30.73,
      },
      {
        id: "uk-7",
        dtg: "21 SEP",
        location: "KHARKIV",
        fact: "OSINT (@war_cube / JHArnous): geolocated strike on Epicentr, Kharkiv 49.908390, 36.275573. Stills show ISR reticle + blurred aftermath overlay. Site name not independently confirmed here.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 49.90839,
        lon: 36.275573,
      },
      {
        id: "uk-8",
        dtg: "21 SEP",
        location: "ODESA",
        fact: "OSINT (@war_cube / JHArnous): unknown warehouse hit at 46.524836, 30.602931. Aligns with SES/OVA warehouse-fire reporting; specific building is a geolocation CLAIM.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 46.524836,
        lon: 30.602931,
      },
      {
        id: "uk-9",
        dtg: "21 SEP",
        location: "NOVOALEKSANDROVKA",
        fact: "RV voenkor map: 128 OMSBr took Novoaleksandrovka (Vovchansk raion) from Ukraine\u2019s 129th. Single-source MIL CLAIM \u2014 no independent confirmation in this pass. Village pin only, no control-line.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 50.15739,
        lon: 37.24777,
      },
      {
        id: "uk-10",
        dtg: "21 SEP",
        location: "POLNAYA",
        fact: "RV voenkor map: 82 MSP took Polnaya after 57th OMBr. Same single-source claim as Novoaleksandrovka. Village pin only.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 50.16157,
        lon: 36.98636,
      },
    ],
    markers: [
      { id: "kapotnya", name: "KAPOTNYA ORF", lat: 55.635, lon: 37.795, note: "ORF hit / fire", tone: "hot" },
      { id: "moscow", name: "MOSCOW", lat: 55.75, lon: 37.62, note: "Fuel hub hit 5\u20136 Oct", tone: "hot" },
      { id: "kyiv", name: "KYIV", lat: 50.45, lon: 30.52, note: "Darnytskyi 7 Oct; Academy 28 Sep", tone: "hot" },
      { id: "pokrovsk", name: "POKROVSK AXIS", lat: 48.28, lon: 37.18, note: "HOLD", tone: "warn" },
      { id: "blacksea", name: "BLACK SEA", lat: 45.3, lon: 32.5, note: "Ship sinkings 5\u20136 Oct (area)", tone: "warn" },
      { id: "zaporizhzhia", name: "ZAPORIZHZHIA", lat: 47.84, lon: 35.14, note: "Dnipro bridge strike 6 Oct", tone: "warn" },
      { id: "odesa", name: "ODESA", lat: 46.48, lon: 30.73, note: "Warehouse fires (OVA)", tone: "warn" },
      { id: "kharkiv-epicentr", name: "KHARKIV EPICENTR", lat: 49.90839, lon: 36.275573, note: "OSINT geoloc CLAIM", tone: "dim" },
      { id: "odesa-wh", name: "ODESA WAREHOUSE", lat: 46.524836, lon: 30.602931, note: "OSINT geoloc CLAIM", tone: "dim" },
      { id: "novoaleks", name: "NOVOALEKSANDROVKA", lat: 50.15739, lon: 37.24777, note: "RV capture CLAIM", tone: "dim" },
      { id: "polnaya", name: "POLNAYA", lat: 50.16157, lon: 36.98636, note: "RV capture CLAIM", tone: "dim" },
      { id: "chuhuiv", name: "CHUHUIV DIST.", lat: 49.84, lon: 36.68, note: "Farm strike 6 dead 24 Sep", tone: "hot" },
      { id: "pryluky", name: "PRYLUKY", lat: 50.595, lon: 32.387, note: "Residential block hit 7 Oct", tone: "hot" },
      { id: "volgograd", name: "VOLGOGRAD", lat: 48.708, lon: 44.515, note: "Refinery halted 2 Oct", tone: "hot" },
      { id: "lyman", name: "LYMAN AXIS", lat: 48.98, lon: 37.817, note: "UA gains N/NE (ISW)", tone: "warn" },
    ],
  };
