import type { Theater } from "./sitrep.types";

export const THEATER_OVERVIEW: Theater =   {
    id: "overview",
    name: "OVERVIEW",
    short: "GLOBAL",
    status: "HORMUZ TANKER WAR / YEMEN FRONT",
    pip: "hot",
    map: { lat: 24.5, lon: 42, zoom: 3 },
    kpis: [
      { label: "PRIORITY THEATER", value: "IRAN / GULF", tone: "hot" },
      { label: "HORMUZ", value: "12 HITS / WK", tone: "hot" },
      { label: "YEMEN\u2013KSA", value: "AIRPORTS HIT", tone: "hot" },
      { label: "UKRAINE", value: "07 OCT MASS STRIKE", tone: "hot" },
    ],
    watch: [
      "Hormuz tanker war: record week + UKMTO 158-26 north of Qatar",
      "US buildup (3rd CSG) vs post-midterm strike talk; Qatar channel",
      "Yemen: Mocha/Dhubab DELTA, Taiz siege, Houthi strikes on Saudi airports",
      "Ukraine: 7 Oct mass strike aftermath; Black Sea ship attacks",
      "Pak\u2013Afghan: 30 Sep\u20131 Oct strikes, UNAMA civilian toll",
      "Sudan: Burhan rejects talks; drone strikes on Damazin / El Obeid",
    ],
    events: [
      {
        id: "ov-158",
        dtg: "07 OCT",
        location: "GULF / N OF QATAR",
        fact: "UKMTO 158-26 (1900Z): tanker 51 nm north of Madinat ash Shamal, Qatar, struck by multiple projectiles; casualties reported (no number); no attribution. Gulf area pin only.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 27.0,
        lon: 51.0,
      },
      {
        id: "ov-ukr-0710",
        dtg: "07 OCT",
        location: "PRYLUKY / UKRAINE",
        fact: "Ukr AF (Al Jazeera): 130 drones, 48 cruise + ballistic missiles overnight, 161 downed; Zelenskyy: energy a key target. Kyiv Independent: Pryluky apartment block hit \u2014 at least 19 killed incl. 5 children, 55 injured; 3 killed in Kyiv. RU MoD: strike on military-industrial sites.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 50.595,
        lon: 32.387,
      },
      {
        id: "ov-aden",
        dtg: "07 OCT",
        location: "ADEN",
        fact: "Yemen Transport Ministry (Al Jazeera/Reuters): ballistic missiles and drones targeted Aden airport, one landed near the runway; no casualties (Aden security, AP). Houthis say they targeted Saudi military supplies near the airport.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 12.79,
        lon: 45.029,
      },
      {
        id: "ov-saudi-air",
        dtg: "06\u201307 OCT",
        location: "ABHA / RIYADH KKIA",
        fact: "AP: Saudi GACA \u2014 attacks on Abha airport and King Khalid airport killed 3 residents and wounded 36; Houthis claimed both. Coalition: missile intercepted north of Riyadh. Reuters 5 Oct: Saudi Arabia, Turkey, Pakistan agree rapid force deployment under the Mecca Joint Defence Agreement.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 18.216,
        lon: 42.504,
      },
      {
        id: "ov-burqa",
        dtg: "07 OCT",
        location: "BURQA / NABLUS",
        fact: "AFP: Palestinian health ministry \u2014 Ali al-Bazzari, 44, killed and 9 injured in a settler attack followed by army intervention in Burqa; IDF says a commander \u201cneutralised\u201d a man running at him with a suspicious object.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 32.299,
        lon: 35.195,
      },
      {
        id: "ov-naqdi",
        dtg: "07 OCT",
        location: "TEHRAN",
        fact: "Reuters (citing Fars): IRGC adviser Naqdi \u2014 Hormuz \u201cclosed\u201d until demands met; Oman-side \u201cillegal routes\u201d to be blocked soon. Ghalibaf (4 Oct): seven conditions first. Qatar MFA (6 Oct): indirect message exchanges continue via Qatar.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 35.69,
        lon: 51.39,
      },
      {
        id: "ov-sudan-damazin",
        dtg: "07 OCT",
        location: "ED DAMAZIN",
        fact: "Emergency Lawyers (AP): drone strike on Hijra neighbourhood killed at least 4 women, wounded dozens; blames RSF, RSF no comment. Burhan (SUNA, 6 Oct): rejects negotiations, vows to retake \u201cevery inch.\u201d",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 11.807,
        lon: 34.366,
      },
      {
        id: "ov-tanker-week",
        dtg: "28 SEP\u201306 OCT",
        location: "HORMUZ",
        fact: "Reuters (three maritime security sources): at least 12 tanker attacks 28 Sep\u20135 Oct, highest weekly count of the war; IMO: 9. 6 Oct: ON PEACE struck off Musandam, 12 of 19 crew injured (India MEA); Oman air force evacuated 10 crew. No attribution.",
        source: "OPEN COMP",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ov-mocha",
        dtg: "05\u201307 OCT",
        location: "MOCHA / DHUBAB",
        fact: "Reuters/AFP/AP: Yemeni govt says forces retook coast up to Mocha and Dhubab airstrip; AFP sources say Mocha besieged, not taken; Houthi officials claim they regained Dhubab and Bab el-Mandeb, govt denies. Control DELTA.",
        source: "PRESS",
        confidence: "DELTA",
        priority: "PRI-1",
        lat: 13.318,
        lon: 43.25,
      },
      {
        id: "ov-blacksea",
        dtg: "05\u201306 OCT",
        location: "W. BLACK SEA",
        fact: "Bulgarian PM Radev (Reuters): drones hit two merchant ships ~70 nm off Byala in Bulgaria\u2019s EEZ, ALFA WATAN sank; Romania (via ISW): ship fire south of Sfantu Gheorghe, 2 dead, sank. Origin disputed (Zelenskyy: Russia; Radev unsure). Area pin only.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 45.3,
        lon: 32.5,
      },
      {
        id: "ov-af-0930",
        dtg: "30 SEP\u201301 OCT",
        location: "KUNAR / HELMAND",
        fact: "RFE/RL + FDD LWJ: Pakistani strikes in Kunar and Helmand; Pakistan claims 22 militants killed; UNAMA: 10 civilians killed, mostly children. Garmsir district pin only.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 30.852,
        lon: 64.172,
      },
      {
        id: "ov-iraq-exit",
        dtg: "30 SEP",
        location: "ERBIL",
        fact: "Pentagon spox Parnell (Al Jazeera; CENTCOM): last US/coalition troops left Erbil Air Base; OIR Iraq mission ended, task force moved to Jordan.",
        source: "STATE",
        confidence: "CONFIRMED",
        priority: "PRI-2",
        lat: 36.191,
        lon: 44.009,
      },
      {
        id: "ov-us-track",
        dtg: "26 SEP\u201306 OCT",
        location: "WASHINGTON",
        fact: "Trump rejected Iran\u2019s proposal (26 Sep, Guardian/Reuters/AP). WSJ via Stars and Stripes: third carrier strike group + MEU by end-November; Trump to Time: strikes \u201cpossible\u201d after the midterms. Vance (Reuters): deal needs movement on enrichment.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 38.895,
        lon: -77.036,
      },
      {
        id: "ov-af-strikes",
        dtg: "24 SEP",
        location: "KANDAHAR / PAKTIA / KHOST",
        fact: "Pakistan says precision air/drone strikes on 10 Afghan sites used to store/launch drones after a 23 Sep drone incursion claim (Info Min Tarar / AJ-AFP-AP-Reuters). Taliban spokesman Mujahid: at least 4 dead; denies Kabul launched the drones. Kandahar city pin \u2014 not a depot geolocation.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 31.63,
        lon: 65.74,
      },
      {
        id: "ov-cape-dao",
        dtg: "23 SEP",
        location: "HORMUZ / MUSANDAM",
        fact: "UKMTO: cargo vessel struck by unknown projectile, on fire/adrift, crew evacuated (2 casualties in initial note). Oman Maritime Security: Antigua/Barbuda-flagged CAPE DAO ~2.5 nm off Musandam; engine-room fire; 1 crew dead, 27 evacuated. No claim of responsibility.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ov-erbil",
        dtg: "20 SEP",
        location: "ERBIL",
        fact: "Hebrew Telegram: UAV hit near US consulate in Erbil. Greek press same cycle: drone downed near Erbil airport / coalition presence. Plume still is not a geolocation. City pin only \u2014 consulate vs airport is DELTA.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 36.191,
        lon: 44.009,
      },
    ],
    markers: [
      { id: "m-iran", name: "IRAN / GULF", lat: 27.1, lon: 56.3, note: "12 hits/wk; Naqdi \u201cclosed\u201d", tone: "hot" },
      { id: "m-riyadh", name: "RIYADH", lat: 24.71, lon: 46.68, note: "Intercept N of Riyadh 7 Oct", tone: "warn" },
      { id: "m-kkia", name: "KKIA FUEL", lat: 24.958, lon: 46.699, note: "1 killed 7 Oct (GACA)", tone: "hot" },
      { id: "m-wb", name: "WEST BANK", lat: 32, lon: 35.2, note: "Burqa 1 killed 7 Oct", tone: "warn" },
      { id: "m-ukr", name: "UKRAINE", lat: 48.4, lon: 35, note: "Mass strike 7 Oct", tone: "hot" },
      { id: "m-kohat", name: "KOHAT / AFPAK", lat: 33.59, lon: 71.44, note: "18 Sep attack, 31 dead", tone: "hot" },
      { id: "m-kandahar", name: "KANDAHAR", lat: 31.63, lon: 65.74, note: "Strikes 24 Sep; ISPR CLAIM", tone: "hot" },
      { id: "m-sud", name: "SUDAN", lat: 15.5, lon: 32.5, note: "SAF / RSF drone war", tone: "hot" },
      { id: "m-taiz", name: "TAIZ", lat: 13.58, lon: 44.02, note: "Encirclement (Reuters); market CLAIM", tone: "warn" },
      { id: "m-erbil", name: "ERBIL", lat: 36.191, lon: 44.009, note: "UAV CLAIM 20 Sep; US exit 30 Sep", tone: "dim" },
      { id: "m-aden", name: "ADEN", lat: 12.79, lon: 45.029, note: "Airport attack 7 Oct", tone: "hot" },
      { id: "m-abha", name: "ABHA", lat: 18.216, lon: 42.504, note: "Airport attack, deaths", tone: "hot" },
      { id: "m-mocha", name: "MOCHA", lat: 13.318, lon: 43.25, note: "Control DELTA", tone: "warn" },
      { id: "m-pryluky", name: "PRYLUKY", lat: 50.595, lon: 32.387, note: "Mass strike 7 Oct", tone: "hot" },
      { id: "m-garmsir", name: "GARMSIR (DIST.)", lat: 30.852, lon: 64.172, note: "Pak strike 30 Sep\u20131 Oct", tone: "hot" },
      { id: "m-damazin", name: "ED DAMAZIN", lat: 11.807, lon: 34.366, note: "Drone strike 7 Oct", tone: "hot" },
    ],
  };
