import type { Theater } from "./sitrep.types";

export const THEATER_LEVANT: Theater =   {
    id: "levant",
    name: "LEVANT",
    short: "LEVANT",
    status: "WB ACTIVE / LEB OCC",
    pip: "warn",
    map: { lat: 32.6, lon: 35.4, zoom: 7 },
    kpis: [
      { label: "LEBANON", value: "CEASEFIRE / OCC", tone: "warn" },
      { label: "WEST BANK", value: "ACTIVE", tone: "hot" },
      { label: "GAZA", value: "YELLOW LINE", tone: "dim" },
      { label: "HOUTHI\u2013KSA", value: "AIR RAID", tone: "warn" },
    ],
    watch: [
      "Yellow Line crossings in Gaza",
      "South Lebanon occupation incidents",
      "West Bank outpost / shooting cycle",
      "Houthi follow-on vs Riyadh / energy",
      "Taiz market-strike CLAIM — city pin only, no site geolocation",
      "Al-Madaribah Giants UAV CLAIM — district pin only, no pickup geolocation",
      "IDF activity Daraa/Quneitra buffer",
      "Al-Eis depot blasts — cause still investigated, not attributed",
      "Khiam / south Lebanon demolition cycle",
    ],
    events: [
      {
        id: "lv-mansouri",
        dtg: "21 SEP",
        location: "MANSOURI / DEIR SIRYAN",
        fact: "Telegram (301 Arab World): smoke plumes over Deir Siryan and al-Mansouri, south Lebanon. Stills show distant white columns only — no munition ID. Press already had IDF fire on Mansouri; this clip is CLAIM for these two towns.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 33.178,
        lon: 35.214,
      },
      {
        id: "lv-burqin",
        dtg: "21 SEP",
        location: "BURQIN",
        fact: "Telegram (301 Arab World): clashes in Burqin, Jenin — stones thrown at Israeli forces. Clip not independently corroborated here.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-3",
        lat: 32.456,
        lon: 35.26,
      },
      {
        id: "lv-silwan",
        dtg: "21 SEP",
        location: "SILWAN",
        fact: "Telegram (301 Arab World): clashes in Silwan now. Clip not independently corroborated here.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-3",
        lat: 31.77,
        lon: 35.237,
      },
      {
        id: "lv-tuffah",
        dtg: "21 SEP",
        location: "GAZA / TUFFAH",
        fact: "Telegram (301 Arab World): UAV strike in Tuffah, east Gaza City; one killed. Press TV same neighborhood: warplanes hit a residential building. Collage (night plume + later rubble) is not a building geolocation. Neighborhood pin only.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.506,
        lon: 34.466,
      },
      {
        id: "lv-shujaiyya",
        dtg: "21 SEP",
        location: "SHUJA'IYYA",
        fact: "Hebrew Telegram (@ramreports): strike on a ‘terror target’ behind the courthouse mosque, east of Shuja'iyya junction, east Gaza City. Night plume is not a geolocation. Neighborhood pin only — not the mosque.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.501,
        lon: 34.468,
      },
      {
        id: "lv-khanyounis",
        dtg: "21 SEP",
        location: "KHAN YOUNIS",
        fact: "Militant Telegram: IDF demolition in southern Khan Younis. Caption-only, no clip geolocation this pass. City-south pin — not a building.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.344,
        lon: 34.303,
      },
      {
        id: "lv-taiz",
        dtg: "21 SEP",
        location: "TAIZ",
        fact: "Houthi-aligned Telegram (@sarzaminkhanjarha): Saudi strike on a local market in Taiz. Clip: outdoor gathering + fireball, camera overlay. Unverified attribution/site. City pin only — no market geolocation.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 13.58,
        lon: 44.02,
      },
      {
        id: "lv-madaribah",
        dtg: "21 SEP",
        location: "AL-MADARIBAH",
        fact: "Hebrew Telegram (Hananel Aviv): Southern Giants claim UAV hits on Houthi cells and military pickups on the Al-Wazia–Al-Madaribah front, west Lahij near Bab al-Mandeb. Clip not independently geolocated. District pin only — not a vehicle, not a control-line. Arab News 20 Sep: Nation’s Shield / Giants fighting and a drone downed near Kahboub Mountain in Al-Madaribah Wa Al-Aarah — related district fight, not this clip.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 12.72,
        lon: 43.9,
      },
      {
        id: "lv-6",
        dtg: "21 SEP",
        location: "DARAA / YARMOUK",
        fact: "IDF artillery + MG fire on Wadi Abidin, Wadi al-Raqqad, outskirts of Jamla (Yarmouk Basin), western Daraa. Tip via IRNA Telegram; Anadolu/SANA/ANHA same. No casualties reported.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 32.67,
        lon: 35.88,
      },
      {
        id: "lv-1",
        dtg: "20 SEP",
        location: "RIYADH",
        fact: "Houthi missile toward Riyadh intercepted. Riyadh hosting Red Sea shipping-protection naval meeting.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.71,
        lon: 46.68,
      },
      {
        id: "lv-kkia",
        dtg: "19\u201321 SEP",
        location: "RIYADH KKIA",
        fact: "Press: Houthi strike on King Khalid Airport jet-fuel tanks; flights disrupted. Telegram satellite (Merrux) circles a tank farm \u2014 oval BDA is CLAIM, not a damage assessment.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.958,
        lon: 46.699,
      },
      {
        id: "lv-2",
        dtg: "20 SEP",
        location: "NEVE TZU",
        fact: "Yom Kippur Eve shooting at a spring near Neve Tzuf/Halamish. Shooter later detained after a hospital raid.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 32.04,
        lon: 35.12,
      },
      {
        id: "lv-3",
        dtg: "20 SEP",
        location: "JENIN",
        fact: "IDF killed a Palestinian near new Ganim outpost; claimed ramming attempt.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 32.46,
        lon: 35.3,
      },
      {
        id: "lv-4",
        dtg: "PRIOR",
        location: "GAZA",
        fact: "IDF reported killing 2 in the north after a Yellow Line crossing. Katz prior: energy-infra strike threat if Iran hits Israel.",
        source: "MIL CLAIM",
        confidence: "HOLD",
        priority: "PRI-3",
        lat: 31.5,
        lon: 34.47,
      },
      {
        id: "lv-khiam",
        dtg: "23 SEP",
        location: "KHIAM",
        fact: "Al-Monitor / NNA: Israeli forces carried out a series of explosions in al-Khiam (Nabatiyeh) overnight; power lines damaged; outages reported in Hasbaya, Shebaa, al-Arqoub. Material damage in Khiam and nearby towns; a Marjeyoun-area school suspended classes.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.33,
        lon: 35.61,
      },
      {
        id: "lv-5",
        dtg: "20\u201321 SEP",
        location: "ALEPPO / AL-EIS",
        fact: "Named press now corroborates ammo-depot blasts: Reuters/AFP 21 Sep — series of explosions at Syrian army weapons depot near Al-Eis, southern Aleppo countryside; 4 hurt (SANA/Emergency Ministry). Earlier 20 Sep OSINT tip (@IntelSlava) stays as lead-in. Countryside/city pin only \u2014 no depot geolocation; no attack attribution in named press.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 36.2,
        lon: 37.16,
      },
    ],
    markers: [
      { id: "kkia", name: "KKIA FUEL", lat: 24.958, lon: 46.699, note: "Jet-fuel tanks 19\u201320 Sep", tone: "hot" },
      { id: "sleb", name: "SOUTH LEBANON", lat: 33.2, lon: 35.3, note: "Occupation / Litani", tone: "warn" },
      { id: "mansouri", name: "MANSOURI", lat: 33.178, lon: 35.214, note: "Smoke CLAIM 21 Sep", tone: "warn" },
      { id: "deir-siryan", name: "DEIR SIRYAN", lat: 33.283, lon: 35.533, note: "Smoke CLAIM 21 Sep", tone: "warn" },
      { id: "jenin", name: "JENIN / GANIM", lat: 32.46, lon: 35.3, note: "Outpost incident", tone: "hot" },
      { id: "burqin", name: "BURQIN", lat: 32.456, lon: 35.26, note: "Clashes CLAIM", tone: "warn" },
      { id: "gaza", name: "GAZA", lat: 31.5, lon: 34.47, note: "Yellow Line", tone: "dim" },
      { id: "khan-younis", name: "KHAN YOUNIS", lat: 31.344, lon: 34.303, note: "Demolition CLAIM", tone: "warn" },
      { id: "tuffah", name: "TUFFAH", lat: 31.506, lon: 34.466, note: "UAV CLAIM 21 Sep", tone: "hot" },
      { id: "shujaiyya", name: "SHUJA'IYYA", lat: 31.501, lon: 34.468, note: "Strike CLAIM 21 Sep", tone: "warn" },
      { id: "halamish", name: "HALAMISH", lat: 32.04, lon: 35.12, note: "Shooting", tone: "hot" },
      { id: "silwan", name: "SILWAN", lat: 31.77, lon: 35.237, note: "Clashes CLAIM", tone: "warn" },
      { id: "aleppo", name: "ALEPPO", lat: 36.2, lon: 37.16, note: "Al-Eis depot blasts (press)", tone: "warn" },
      { id: "khiam", name: "KHIAM", lat: 33.33, lon: 35.61, note: "IDF explosions 23 Sep", tone: "warn" },
      { id: "daraa-yarmouk", name: "DARAA / YARMOUK", lat: 32.67, lon: 35.88, note: "IDF shelling 21 Sep", tone: "warn" },
      { id: "taiz", name: "TAIZ", lat: 13.58, lon: 44.02, note: "Market-strike CLAIM 21 Sep", tone: "warn" },
      { id: "madaribah", name: "AL-MADARIBAH", lat: 12.72, lon: 43.9, note: "Giants UAV CLAIM 21 Sep", tone: "warn" },
    ],
  };
