import type { Theater } from "./sitrep.types";

export const THEATER_SUDAN: Theater =   {
    id: "sudan",
    name: "SUDAN",
    short: "SUDAN",
    status: "N. KORDOFAN GAINS / BLUE NILE PUSH",
    pip: "hot",
    map: { lat: 15.5, lon: 32, zoom: 5.5 },
    kpis: [
      { label: "WAR", value: "SAF vs RSF", tone: "hot" },
      { label: "CONTROL", value: "SAF N/E/CTR \u00b7 RSF DARFUR", tone: "warn" },
      { label: "N. KORDOFAN", value: "SAF MOST LOCALITIES", tone: "warn" },
      { label: "BLUE NILE", value: "TA'SIS PUSH (DELTA)", tone: "hot" },
      { label: "DRONE STRIKES", value: "DAMAZIN / EL OBEID", tone: "hot" },
    ],
    watch: [
      "SAF Al-Khuwei axis offensive (Sudan Times) / push toward En Nahud \u2014 RSF massing in West Kordofan (Al Jazeera)",
      "RSF pockets around El Obeid: Abu Qa'ud, Umm Sumaima, Kazgil (Sudans Post)",
      "Blue Nile: Ta'sis claims in Roseires / Wad al-Mahi vs SAF 4th Div \u2014 IOM displacement",
      "Drone strikes on cities: Damazin, El Obeid, Dilling \u2014 attribution",
      "West Darfur: Joint Force Bir Saliba CLAIM \u2014 RSF response",
      "Burhan \u201cevery inch\u201d vs Boulos Sudanese-led dialogue; New Alamein quad declaration",
      "Darfur food gaps: 7.1M of 9.1M may lack aid in Q4 (OCHA)",
    ],
    events: [
      {
        id: "sd-damazin",
        dtg: "07 OCT",
        location: "ED DAMAZIN",
        fact: "Emergency Lawyers (AP via Al Arabiya; Daily Sabah): drone strike on Hijra neighbourhood killed at least 4 women and wounded dozens, hitting homes and a mosque; group blames RSF, RSF has not commented. IOM (Al Jazeera): 5,500+ displaced in Blue Nile over 3 days. City pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 11.807,
        lon: 34.366,
      },
      {
        id: "sd-bluenile",
        dtg: "03\u201307 OCT",
        location: "ROSEIRES / WAD AL-MAHI",
        fact: "Radio Dabanga 4 Oct: RSF-aligned Ta'sis Alliance says it took full control of areas in Roseires locality incl. Menze, Jabal El Nimr, Basharkat, Matanguya and Makala, claiming 20+ vehicles and many prisoners; SAF 4th Infantry Division says it dealt a \u201cdecisive blow\u201d to RSF/SPLM-N at Menze and Basharkat. Control DELTA. Blue Nile governor (Facebook, via Dabanga): RSF suicide drones targeted his Ed Damazin home 3 Oct. IOM (Anadolu 7 Oct): 1,275 fled Wad al-Mahi villages on 6 Oct, 6,800 in 4 days; OCHA: 10,000+ displaced in the state 26 Sep\u20134 Oct. Er Roseires town pin \u2014 not the villages.",
        source: "PRESS",
        confidence: "DELTA",
        priority: "PRI-1",
        lat: 11.863,
        lon: 34.388,
      },
      {
        id: "sd-burhan",
        dtg: "05\u201306 OCT",
        location: "MEROWE / EGYPT",
        fact: "SUNA (via Al Jazeera, Daily Sabah): Burhan, in Merowe locality, vows to retake \u201cevery inch\u201d and rejects negotiations. Reuters (via Al-Monitor): US envoy Boulos attended a Sisi-hosted lunch in Egypt with Burhan \u2014 a Sudanese official called it a \u201ccasual encounter,\u201d no talks; Boulos backs a Sudanese-led dialogue. Merowe pin.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 18.481,
        lon: 31.817,
      },
      {
        id: "sd-khuwei",
        dtg: "07 OCT",
        location: "AL-KHUWEI (W. KORDOFAN)",
        fact: "Sudan Times 7 Oct, citing military sources via Independent Arabia: army began operations on the Al-Khuwei axis in West Kordofan, with heavy artillery supporting forces around Al-Khuwei and air/artillery strikes on RSF positions and supply routes around Umm Kureidim. Sudan Times: no independently verified confirmation of major territorial changes around Al-Khuwei; RSF had not responded. Al Jazeera 7 Oct: army advancing toward En Nahud and Al Khuway as RSF masses in West Kordofan. Al Khiwai town pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 13.084,
        lon: 29.217,
      },
      {
        id: "sd-abu-ajal",
        dtg: "06 OCT",
        location: "EN NAHUD AREA",
        fact: "Al Jazeera: Dar Hamar Emergency Committee says an RSF attack killed 10 civilians in Abu Ajal village, southeast of En Nahud (RSF comment not seen); army advancing toward En Nahud and Al Khuwei. En Nahud town pin \u2014 not the village.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 12.692,
        lon: 28.422,
      },
      {
        id: "sd-bir-saliba",
        dtg: "06 OCT",
        location: "WEST DARFUR",
        fact: "Joint Force of Armed Movements statement (via Anadolu): army and Joint Force took Bir Sleiba on the northern route to El Geneina after \u201cfierce field battles\u201d on the Bir Sleiba and Abu Suruj fronts, claiming 7 RSF vehicles destroyed. Army/Joint Force personnel posted videos (not independently geolocated in sources read). RSF has not commented. Gazetteer pin for Bersiliba town.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 13.974,
        lon: 22.375,
      },
      {
        id: "sd-2",
        dtg: "03\u201306 OCT",
        location: "SUDAN",
        fact: "Control map refresh (supersedes 7 Sep): Al Jazeera 1 & 4 Oct \u2014 SAF holds Khartoum and most of the north, east and centre; RSF holds almost all of Darfur and parts of Kordofan (West Kordofan an RSF stronghold); South Kordofan contested; RSF-allied SPLM-N (al-Hilu) holds pockets in the south. Anadolu 6 Oct: RSF controls the five Darfur states except parts of North and West Darfur under army control. Sudans Post 2 Oct: after Mazroub, RSF still holds positions in parts of Sodari (Umm Badr, Hamrat al-Sheikh) and Sheikan (Abu Qa'ud, Umm Sumaima, Kazgil) localities. Edges are fluid. Theater map-centre pin.",
        source: "OPEN COMP",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 15.5,
        lon: 32,
      },
      {
        id: "sd-mazroub",
        dtg: "02 OCT",
        location: "AL-MAZROUB",
        fact: "Sudans Post 2 Oct: army seized Mazroub, West Bara locality HQ, from the RSF; videos geolocated by Sudans Post show SAF personnel outside the Mazroub court in the town centre and Joint Force fighters in an open area south of town. Army statement claims heavy RSF losses (no figures; Sudans Post could not verify). Anadolu 2 Oct: army special-forces spokesman Mohamed Deidan says the army \u201chas taken full control of Al-Mazroub\u201d, a link between North and West Kordofan; Dar Hamar Emergency Response Room also announced the capture. RSF had not commented. Town pin.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 13.902,
        lon: 29.319,
      },
      {
        id: "sd-alamein",
        dtg: "04 OCT",
        location: "NEW ALAMEIN, EGYPT",
        fact: "Al Jazeera: Burhan, Sisi, Isaias and Hassan Sheikh Mohamud issued a joint declaration backing Sudan's military-led government and a Sudanese-led political process; Eritrea MoI (shabait, via CTP) published the text. Ethiopia accuses Egypt, Eritrea and Sudan of backing its armed opposition; all three deny. City pin.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-2",
        lat: 30.87,
        lon: 28.899,
      },
      {
        id: "sd-wfp",
        dtg: "03 OCT",
        location: "DILLING / KADUGLI ROAD",
        fact: "UN News / WFP: airstrike hit two marked WFP-contracted trucks between Dilling and Kadugli, killing a driver; no attribution. Day before, a WFP truck hit an explosive device in Dilling. OCHA 5 Oct: Fletcher calls the killing \u201cunacceptable\u201d. Sudan War Monitor (Arabic, 6 Oct): Ta'sis Alliance blames the army. Dilling town pin \u2014 not the strike site.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 12.04,
        lon: 29.654,
      },
      {
        id: "sd-el-obeid",
        dtg: "30 SEP\u201301 OCT",
        location: "EL OBEID",
        fact: "AFP (via Ahram): 30 Sep drone hit a University of Kordofan dormitory, 5 killed, 47 wounded (Emergency Lawyers; no attribution); 1 Oct drone hit a shelter for displaced families, 5 killed, 13 injured (North Kordofan official blames RSF). UNICEF (via OCHA 5 Oct) for 1 Oct: one child killed, 12 others injured. City pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 13.183,
        lon: 30.223,
      },
      {
        id: "sd-sodari",
        dtg: "25 SEP",
        location: "SODARI",
        fact: "Sudans Post (26 Sep; 2 Oct): army and Joint Force captured Sodari town on Fri 25 Sep, the locality HQ; geolocated video shows fighters at a fuel station and the health-insurance office. Anadolu 2 Oct: army declared control of Sodari the day before announcing Um Sharo (26 Sep). RSF still holds Umm Badr and Hamrat al-Sheikh to the northwest. Sudans Post sources allege ~17 prisoners were killed on entry; army statement did not address prisoners \u2014 unverified. Town pin.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-2",
        lat: 14.412,
        lon: 29.103,
      },
      {
        id: "sd-visa",
        dtg: "22 SEP",
        location: "NEW YORK / PORT SUDAN",
        fact: "Reuters: US withholding Burhan UNGA visa; Sudanese/Western sources link attendance to accepting Massad Boulos 90-day ceasefire. Sudan UN ambassador letter 21 Sep asks Guterres to intervene. UN spokesperson deeply concerned.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 40.75,
        lon: -73.97,
      },
      {
        id: "sd-legit",
        dtg: "23 SEP",
        location: "NEW YORK",
        fact: "Reuters/State: spokesman Pigott says neither SAF nor RSF leaders represent legitimate constitutional governance. Sudan MFA rejects US remarks. Rubio: Sudan mediation \u201cfrustrating\u201d \u2014 commitments unmet.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 40.75,
        lon: -73.97,
      },
      {
        id: "sd-darfur-aid",
        dtg: "05 OCT",
        location: "DARFUR",
        fact: "OCHA: below-average rain worsens Darfur needs; food partners estimate 7.1M of the 9.1M people expected to need food aid in Q4 could face gaps; emergency acute-malnutrition levels across much of the region. IRC: support cut for 473,000+ people nationwide. Theater map-centre pin \u2014 region-wide item, not located.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 15.5,
        lon: 32,
      },
      {
        id: "sd-3",
        dtg: "PRIOR",
        location: "EL FASHER",
        fact: "UN FFM: hallmarks of genocide at El-Fasher/Zamzam; up to ~2,000 former Colombian contractors with RSF; foreign drones both sides.",
        source: "UN FFM",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 13.63,
        lon: 25.35,
      },
    ],
    markers: [
      { id: "khartoum", name: "KHARTOUM", lat: 15.5, lon: 32.53, note: "SAF-held capital (AJ)", tone: "dim" },
      { id: "elfasher", name: "EL FASHER", lat: 13.63, lon: 25.35, note: "RSF since Oct 2025; UN FFM", tone: "hot" },
      { id: "kordofan", name: "N. KORDOFAN", lat: 14.4, lon: 29.5, note: "SAF holds most localities (Sudans Post)", tone: "warn" },
      { id: "mazroub", name: "AL-MAZROUB", lat: 13.902, lon: 29.319, note: "SAF took 2 Oct (Sudans Post geoloc.)", tone: "warn" },
      { id: "sodari", name: "SODARI", lat: 14.412, lon: 29.103, note: "SAF took 25 Sep (Sudans Post)", tone: "warn" },
      { id: "damazin", name: "ED DAMAZIN", lat: 11.807, lon: 34.366, note: "Drone strikes 3 & 7 Oct", tone: "hot" },
      { id: "roseires", name: "ER ROSEIRES", lat: 11.863, lon: 34.388, note: "Blue Nile fight DELTA; IDPs arriving (IOM)", tone: "warn" },
      { id: "el-obeid", name: "EL OBEID", lat: 13.183, lon: 30.223, note: "Drone strikes 30 Sep\u20131 Oct", tone: "hot" },
      { id: "al-khuwei", name: "AL-KHUWEI", lat: 13.084, lon: 29.217, note: "SAF offensive axis 7 Oct (Sudan Times)", tone: "warn" },
      { id: "en-nahud", name: "EN NAHUD", lat: 12.692, lon: 28.422, note: "Abu Ajal attack 6 Oct (area)", tone: "warn" },
      { id: "dilling", name: "DILLING", lat: 12.04, lon: 29.654, note: "WFP convoy hit 3 Oct", tone: "warn" },
      { id: "bir-saliba", name: "BIR SALIBA", lat: 13.974, lon: 22.375, note: "Joint Force capture CLAIM 6 Oct", tone: "dim" },
    ],
  };
