import type { Theater } from "./sitrep.types";

export const THEATER_LEVANT: Theater =   {
    id: "levant",
    name: "LEVANT",
    short: "LEVANT",
    status: "YEMEN COUNTEROFFENSIVE / KSA HIT",
    pip: "hot",
    map: { lat: 32.6, lon: 35.4, zoom: 7 },
    kpis: [
      { label: "LEBANON", value: "CEASEFIRE / OCC", tone: "warn" },
      { label: "WEST BANK", value: "ACTIVE", tone: "hot" },
      { label: "GAZA", value: "STRIKES CONTINUE", tone: "warn" },
      { label: "HOUTHI\u2013KSA", value: "AIRPORTS HIT", tone: "hot" },
    ],
    watch: [
      "Mocha / Dhubab / Bab el-Mandeb control \u2014 govt vs Houthi claims (DELTA)",
      "Taiz encirclement \u2014 al-Turbah / Taiz\u2013Aden road",
      "Houthi strikes on Saudi airports and Aden; Rabigh refinery CLAIM",
      "Mecca Joint Defence Agreement \u2014 Turkish/Pakistani deployments to KSA",
      "West Bank settler violence (Burqa) / shooting cycle",
      "Gaza strikes vs ceasefire toll; south Lebanon buffer-zone ops",
      "Taiz market-strike CLAIM \u2014 city pin only, no site geolocation",
      "Al-Madaribah Giants UAV CLAIM \u2014 district pin only, no pickup geolocation",
      "Al-Eis depot blasts \u2014 cause still investigated, not attributed",
    ],
    events: [
      {
        id: "lv-aden",
        dtg: "07 OCT",
        location: "ADEN",
        fact: "Yemen Transport Ministry (Al Jazeera/Reuters): at least two ballistic missiles plus drones targeted Aden airport runway/terminal; one landed near the runway minutes before a Cairo flight (ministry: diverted to Jeddah; AP/FlightAware: Flight 603 landed 03:30). Aden security (AP): no casualties. Houthis say they targeted \u201cSaudi military supplies\u201d at Badr camp near the airport. City pin.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 12.79,
        lon: 45.029,
      },
      {
        id: "lv-saudi-air",
        dtg: "06\u201307 OCT",
        location: "ABHA / RIYADH KKIA",
        fact: "AP 7 Oct: Saudi GACA \u2014 attack on Abha airport killed Moroccan and Algerian residents and wounded 28; attack on King Khalid airport killed a Sudanese national, wounded 8; Houthis claimed both. Coalition spox al-Malki: ballistic missile intercepted north of Riyadh, launch platform in Sanaa destroyed (AP could not verify). Reuters 5 Oct: Saudi Arabia, Turkey and Pakistan agree to rapidly deploy forces in KSA under the Mecca Joint Defence Agreement. Abha city pin.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 18.216,
        lon: 42.504,
      },
      {
        id: "lv-mocha",
        dtg: "05\u201307 OCT",
        location: "MOCHA / DHUBAB",
        fact: "Reuters 5 Oct: govt says Saudi-backed forces retook the coast around Bab el-Mandeb up to Mocha and Defence Ministry says Mocha fell (Reuters could not verify; Houthis: baseless); Dhubab airstrip taken. AFP 6 Oct: military sources say Mocha supply route cut, capture not confirmed; Giants Brigades report a \u201ctight siege.\u201d AP 7 Oct: two Houthi officials claim they regained Dhubab and Bab el-Mandeb; govt official denies. Control DELTA. Town pin.",
        source: "PRESS",
        confidence: "DELTA",
        priority: "PRI-1",
        lat: 13.318,
        lon: 43.25,
      },
      {
        id: "lv-turbah",
        dtg: "04\u201305 OCT",
        location: "TAIZ / AL-TURBAH",
        fact: "Reuters 5 Oct (govt military sources): Houthis advanced near Taiz (al-Turbah, al-Mawasit) and damaged a culvert on the Taiz\u2013Aden road; sources say Taiz is surrounded (one denies). AP: govt counteroffensive began after rebels seized Turbah. UN (AP): ~1,000 killed, 200k+ displaced; IOM (Reuters): 184k displaced. Town pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 13.213,
        lon: 44.124,
      },
      {
        id: "lv-burqa",
        dtg: "07 OCT",
        location: "BURQA / NABLUS",
        fact: "AFP: Palestinian health ministry \u2014 Ali al-Bazzari, 44, killed and 9 injured in Burqa, north of Nablus, in a settler attack followed by army intervention; al-Bazzari was a PA National Security Forces member. IDF: a commander \u201cneutralised\u201d a man running at him with a suspicious object. Village pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 32.299,
        lon: 35.195,
      },
      {
        id: "lv-gaza-0610",
        dtg: "06 OCT",
        location: "GAZA CITY",
        fact: "Reuters (via Al Arabiya): health officials \u2014 at least 2 killed by Israeli strikes, one near al-Shifa Hospital, Gaza City; IDF said both strikes targeted militants. Gaza health officials: at least 1,400 killed since the October ceasefire. Strip pin only.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 31.5,
        lon: 34.47,
      },
      {
        id: "lv-mansouri-op",
        dtg: "28 SEP",
        location: "MANSOURI",
        fact: "Times of Israel: IDF says it completed an operation in Mansouri (inside its south Lebanon buffer zone; residents told to evacuate ~2 months earlier), destroying 600+ Hezbollah infrastructure sites incl. 8 tunnels, plus dozens of launchers. Figures are IDF\u2019s, not independently verified. Does not corroborate the 21 Sep smoke-clip CLAIM (lv-mansouri). Town pin.",
        source: "MIL CLAIM",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.178,
        lon: 35.214,
      },
      {
        id: "lv-mansouri",
        dtg: "21 SEP",
        location: "MANSOURI / DEIR SIRYAN",
        fact: "Telegram (301 Arab World): smoke plumes over Deir Siryan and al-Mansouri, south Lebanon. Stills show distant white columns only \u2014 no munition ID. Press already had IDF fire on Mansouri; this clip is CLAIM for these two towns.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 33.178,
        lon: 35.214,
      },
      {
        id: "lv-tuffah",
        dtg: "21 SEP",
        location: "GAZA / TUFFAH",
        fact: "Telegram (301 Arab World): UAV strike in Tuffah, east Gaza City; one killed. Press TV same neighborhood: warplanes hit a residential building. Collage (night plume + later rubble) is not a building geolocation. Neighborhood pin only.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.506,
        lon: 34.466,
      },
      {
        id: "lv-shujaiyya",
        dtg: "21 SEP",
        location: "SHUJA'IYYA",
        fact: "Hebrew Telegram (@ramreports): strike on a \u2018terror target\u2019 behind the courthouse mosque, east of Shuja'iyya junction, east Gaza City. Night plume is not a geolocation. Neighborhood pin only \u2014 not the mosque.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.501,
        lon: 34.468,
      },
      {
        id: "lv-khanyounis",
        dtg: "21 SEP",
        location: "KHAN YOUNIS",
        fact: "Militant Telegram: IDF demolition in southern Khan Younis. Caption-only, no clip geolocation this pass. City-south pin \u2014 not a building.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.344,
        lon: 34.303,
      },
      {
        id: "lv-taiz",
        dtg: "21 SEP",
        location: "TAIZ",
        fact: "Houthi-aligned Telegram (@sarzaminkhanjarha): Saudi strike on a local market in Taiz. Clip: outdoor gathering + fireball, camera overlay. Unverified attribution/site. City pin only \u2014 no market geolocation.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 13.58,
        lon: 44.02,
      },
      {
        id: "lv-madaribah",
        dtg: "21 SEP",
        location: "AL-MADARIBAH",
        fact: "Hebrew Telegram (Hananel Aviv): Southern Giants claim UAV hits on Houthi cells and military pickups on the Al-Wazia\u2013Al-Madaribah front, west Lahij near Bab al-Mandeb. Clip not independently geolocated. District pin only \u2014 not a vehicle, not a control-line. Arab News 20 Sep: Nation\u2019s Shield / Giants fighting and a drone downed near Kahboub Mountain in Al-Madaribah Wa Al-Aarah \u2014 related district fight, not this clip.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 12.72,
        lon: 43.9,
      },
      {
        id: "lv-6",
        dtg: "21 SEP",
        location: "DARAA / YARMOUK",
        fact: "IDF artillery + MG fire on Wadi Abidin, Wadi al-Raqqad, outskirts of Jamla (Yarmouk Basin), western Daraa. Tip via IRNA Telegram; Anadolu/SANA/ANHA same. No casualties reported.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 32.67,
        lon: 35.88,
      },
      {
        id: "lv-3",
        dtg: "20 SEP",
        location: "JENIN",
        fact: "IDF killed a Palestinian near new Ganim outpost; claimed ramming attempt.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 32.46,
        lon: 35.3,
      },
      {
        id: "lv-khiam",
        dtg: "23 SEP",
        location: "KHIAM",
        fact: "Al-Monitor / NNA: Israeli forces carried out a series of explosions in al-Khiam (Nabatiyeh) overnight; power lines damaged; outages reported in Hasbaya, Shebaa, al-Arqoub. Material damage in Khiam and nearby towns; a Marjeyoun-area school suspended classes.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.33,
        lon: 35.61,
      },
      {
        id: "lv-5",
        dtg: "20\u201321 SEP",
        location: "ALEPPO / AL-EIS",
        fact: "Named press now corroborates ammo-depot blasts: Reuters/AFP 21 Sep \u2014 series of explosions at Syrian army weapons depot near Al-Eis, southern Aleppo countryside; 4 hurt (SANA/Emergency Ministry). Earlier 20 Sep OSINT tip (@IntelSlava) stays as lead-in. Countryside/city pin only \u2014 no depot geolocation; no attack attribution in named press.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 36.2,
        lon: 37.16,
      },
    ],
    markers: [
      { id: "kkia", name: "KKIA FUEL", lat: 24.958, lon: 46.699, note: "Jet-fuel tanks Sep; 1 killed 7 Oct (GACA)", tone: "hot" },
      { id: "sleb", name: "SOUTH LEBANON", lat: 33.2, lon: 35.3, note: "Occupation / Litani", tone: "warn" },
      { id: "mansouri", name: "MANSOURI", lat: 33.178, lon: 35.214, note: "IDF op 28 Sep; smoke CLAIM 21 Sep", tone: "warn" },
      { id: "deir-siryan", name: "DEIR SIRYAN", lat: 33.283, lon: 35.533, note: "Smoke CLAIM 21 Sep", tone: "dim" },
      { id: "jenin", name: "JENIN / GANIM", lat: 32.46, lon: 35.3, note: "Outpost incident (IDF claim)", tone: "dim" },
      { id: "gaza", name: "GAZA", lat: 31.5, lon: 34.47, note: "Strikes 6 Oct (Reuters)", tone: "warn" },
      { id: "khan-younis", name: "KHAN YOUNIS", lat: 31.344, lon: 34.303, note: "Demolition CLAIM", tone: "dim" },
      { id: "tuffah", name: "TUFFAH", lat: 31.506, lon: 34.466, note: "UAV CLAIM 21 Sep", tone: "dim" },
      { id: "shujaiyya", name: "SHUJA'IYYA", lat: 31.501, lon: 34.468, note: "Strike CLAIM 21 Sep", tone: "dim" },
      { id: "aleppo", name: "ALEPPO", lat: 36.2, lon: 37.16, note: "Al-Eis depot blasts (press)", tone: "warn" },
      { id: "khiam", name: "KHIAM", lat: 33.33, lon: 35.61, note: "IDF explosions 23 Sep", tone: "warn" },
      { id: "daraa-yarmouk", name: "DARAA / YARMOUK", lat: 32.67, lon: 35.88, note: "IDF shelling 21 Sep", tone: "warn" },
      { id: "taiz", name: "TAIZ", lat: 13.58, lon: 44.02, note: "Encirclement (Reuters); market CLAIM 21 Sep", tone: "warn" },
      { id: "madaribah", name: "AL-MADARIBAH", lat: 12.72, lon: 43.9, note: "Giants UAV CLAIM 21 Sep", tone: "dim" },
      { id: "aden", name: "ADEN", lat: 12.79, lon: 45.029, note: "Airport missile/drone attack 7 Oct", tone: "hot" },
      { id: "abha", name: "ABHA", lat: 18.216, lon: 42.504, note: "Airport attack, deaths (GACA)", tone: "hot" },
      { id: "mocha", name: "MOCHA", lat: 13.318, lon: 43.25, note: "Control DELTA", tone: "warn" },
      { id: "dhubab", name: "DHUBAB", lat: 12.943, lon: 43.411, note: "Airstrip retaken (govt); Houthi counter-claim", tone: "warn" },
      { id: "turbah", name: "AL-TURBAH", lat: 13.213, lon: 44.124, note: "Houthi advance / Taiz road cut", tone: "warn" },
      { id: "burqa", name: "BURQA", lat: 32.299, lon: 35.195, note: "1 killed 7 Oct (AFP)", tone: "hot" },
    ],
  };
