import type { Theater } from "./sitrep.types";

export const THEATER_OVERVIEW: Theater =   {
    id: "overview",
    name: "OVERVIEW",
    short: "GLOBAL",
    status: "IRAN CENTER OF GRAVITY",
    pip: "hot",
    map: { lat: 24.5, lon: 42, zoom: 3 },
    kpis: [
      { label: "PRIORITY THEATER", value: "IRAN / GULF", tone: "hot" },
      { label: "HORMUZ", value: "CAPE DAO HIT", tone: "hot" },
      { label: "AFPAK", value: "STRIKES 24 SEP", tone: "hot" },
      { label: "UKRAINE WINDOW", value: "KYIV DAYLIGHT", tone: "hot" },
    ],
    watch: [
      "Does the US actually resume strikes on Iran?",
      "Hormuz: Cape Dao Musandam hit + AIS lows vs Bessent flow claims",
      "Iran UNGA channel / Rezaei 4\u20135-day Hormuz conditions clock",
      "Kyiv daylight / ballistic follow-on vs winter energy cycle",
      "Pak\u2013Afghan: 24 Sep airstrikes (10 sites) after claimed drone incursion",
      "Sudan: Burhan UN visa vs 90-day ceasefire demand",
    ],
    events: [
      {
        id: "ov-kyiv-24",
        dtg: "24 SEP",
        location: "KYIV",
        fact: "Overnight RU missiles/drones: Zelenskyy/Klitschko — 2 dead in Kyiv; Ukr AF cites Zircon/Iskander + 282 drones mainly Kyiv/Odesa (RFE/RL, France24/AFP). Same cycle: Chuhuiv district farm — 6 dead (PM Koretsky). City pin = Kyiv only.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 50.45,
        lon: 30.52,
      },

      {
        id: "ov-af-strikes",
        dtg: "24 SEP",
        location: "KANDAHAR / PAKTIA / KHOST",
        fact: "Pakistan says precision air/drone strikes on 10 Afghan sites used to store/launch drones after a 23 Sep drone incursion claim (Info Min Tarar / AJ-AFP-AP-Reuters). Taliban spokesman Mujahid: at least 4 dead; denies Kabul launched the drones. Kandahar city pin — not a depot geolocation.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 31.63,
        lon: 65.74,
      },
      {
        id: "ov-cape-dao",
        dtg: "23 SEP",
        location: "HORMUZ / MUSANDAM",
        fact: "UKMTO: cargo vessel struck by unknown projectile, on fire/adrift, crew evacuated (2 casualties in initial note). Oman Maritime Security: Antigua/Barbuda-flagged CAPE DAO ~2.5 nm off Musandam; engine-room fire; 1 crew dead, 27 evacuated. No claim of responsibility.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ov-kyiv-23",
        dtg: "23 SEP",
        location: "KYIV",
        fact: "AP/Reuters: Russian daylight drone strikes on Kyiv kill 2, wound ~41 ahead of Zelenskyy UNGA address. Hits reported on rail/warehouses/fuel; fires across the capital.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 50.45,
        lon: 30.52,
      },
      {
        id: "ov-iran-unga",
        dtg: "22\u201323 SEP",
        location: "NEW YORK / TEHRAN",
        fact: "Reuters: senior Iranian official — Tehran can reopen Hormuz within 7 days if US eases military pressure and lifts port blockade. Indirect NY talks (Araqchi via Qatar mediators with Witkoff/Kushner); Pezeshkian UNGA: no surrender. Official: sides still far apart.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 40.75,
        lon: -73.97,
      },
      {
        id: "ov-sudan-visa",
        dtg: "22 SEP",
        location: "NEW YORK / PORT SUDAN",
        fact: "Reuters: US withholding Burhan UNGA visa, sources link to acceptance of a Massad Boulos 90-day ceasefire plan Khartoum resists. UN spokesperson \u201cdeeply concerned.\u201d State later: neither SAF nor RSF leaders represent legitimate constitutional governance.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 40.75,
        lon: -73.97,
      },
      {
        id: "ov-daraa",
        dtg: "21 SEP",
        location: "DARAA / YARMOUK",
        fact: "IDF artillery + MG fire on Wadi Abidin, Wadi al-Raqqad, outskirts of Jamla (Yarmouk Basin), western Daraa. Tip via IRNA Telegram; Anadolu/SANA/ANHA same. No casualties reported.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 32.67,
        lon: 35.88,
      },
            {
        id: "ov-ua-1",
        dtg: "20 SEP",
        location: "MOSCOW",
        fact: "UA mass drone wave; Moscow ORF Kapotnya hit; Sobyanin claims 1600+ drones / 450 toward Moscow; 2 dead Moscow region (Reuters).",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.75,
        lon: 37.62,
      },
      {
        id: "ov-af-1",
        dtg: "18\u201319 SEP",
        location: "KOHAT",
        fact: "Suicide VBIED + assault on Police Lines mosque (KP); 20+ dead. Pakistan says attackers had Afghan roots / TTP; Taliban deny. Sanctuary link CLAIM pending stronger corroboration.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.59,
        lon: 71.44,
      },
      {
        id: "ov-af-2",
        dtg: "20 SEP",
        location: "ISLAMABAD / KABUL",
        fact: "Islamabad: hit terrorists wherever they are. Taliban: crushing response IF Pakistan strikes; ask Saudi mediation. Statements REPORTED \u2014 no confirmed new Pak airstrike into Afghanistan 20\u201321 Sep.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.68,
        lon: 73.04,
      },
{
        id: "ov-1",
        dtg: "20 SEP",
        location: "TEHRAN",
        fact: "State media: military command claims intel the US, with some regional backing, is preparing to resume strikes. Threat: sustained hits on US bases; helpers treated as parties.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-1",
        lat: 35.69,
        lon: 51.39,
      },
      {
        id: "ov-2",
        dtg: "20 SEP",
        location: "RIYADH",
        fact: "Houthi missile toward Riyadh intercepted \u2014 first air-raid alert there this round. Ankara backs Saudi security.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.71,
        lon: 46.68,
      },
      {
        id: "ov-kkia",
        dtg: "19\u201321 SEP",
        location: "RIYADH KKIA",
        fact: "Press: Houthi strike on King Khalid Airport fuel storage / jet-fuel tanks; flights disrupted. Telegram satellite (Merrux) circles a tank farm \u2014 oval BDA is CLAIM, not a damage assessment.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.958,
        lon: 46.699,
      },
      {
        id: "ov-erbil",
        dtg: "20 SEP",
        location: "ERBIL",
        fact: "Hebrew Telegram: UAV hit near US consulate in Erbil. Greek press same cycle: drone downed near Erbil airport / coalition presence. Plume still is not a geolocation. City pin only \u2014 consulate vs airport is DELTA.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 36.191,
        lon: 44.009,
      },
      {
        id: "ov-3",
        dtg: "16 SEP",
        location: "HORMUZ",
        fact: "US military says the strait was kept open; tracking/press put shipping at new lows. Claims do not match.",
        source: "MIL CLAIM",
        confidence: "DELTA",
        priority: "PRI-2",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ov-taiz",
        dtg: "21 SEP",
        location: "TAIZ",
        fact: "Houthi-aligned Telegram (@sarzaminkhanjarha): Saudi strike on a local market in Taiz. Clip shows outdoor crowd/vehicles/tents then a fireball; “cmera 01” overlay. Does not prove Saudi, a market, or a specific site. City pin only — no market geolocation.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 13.58,
        lon: 44.02,
      },
      {
        id: "ov-madaribah",
        dtg: "21 SEP",
        location: "AL-MADARIBAH",
        fact: "Hebrew Telegram (Hananel Aviv): Southern Giants claim UAV hits on Houthi cells and military pickups on the Al-Wazia–Al-Madaribah front, west Lahij near Bab al-Mandeb. No strike geolocation. District pin only — not a pickup, not a control-line. Arab News 20 Sep has related fighting / a drone downed near Kahboub Mountain in the same district; that is the district fight, not this clip.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 12.72,
        lon: 43.9,
      },
      {
        id: "ov-7",
        dtg: "21 SEP",
        location: "HORMUZ",
        fact: "UKMTO 141-26: LPG tanker outbound Hormuz hit by debris from unknown projectiles. Crew safe, no spill. Press split inbound/oil/2 injured.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ov-8",
        dtg: "21 SEP",
        location: "ZVIAHEL",
        fact: "Zhytomyr OVA / Ukrinform: Russian strike on a gas station on M-06 near Zviahel. Twice this morning.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 50.59,
        lon: 27.61,
      },
      {
        id: "ov-9",
        dtg: "21 SEP",
        location: "ZAPORIZHZHIA",
        fact: "Ukrainian officials / Zelenskyy: drones hit a shopping center and Zaporizhzhia National University’s oldest building. Odesa: SES/OVA warehouse fires (chain name unconfirmed).",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 47.84,
        lon: 35.14,
      },
      {
        id: "ov-4",
        dtg: "20 SEP",
        location: "WEST BANK",
        fact: "Yom Kippur Eve shooting near Neve Tzuf/Halamish. Israeli man in his 30s critically wounded.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 32.04,
        lon: 35.12,
      },
      {
        id: "ov-5",
        dtg: "20 SEP",
        location: "KYIV",
        fact: "Witkoff still talking a \u201cgood resolution\u201d after Kyiv; pushing trilateral talks. No deal text.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-3",
        lat: 50.45,
        lon: 30.52,
      },
      {
        id: "ov-6",
        dtg: "20 SEP",
        location: "KORDOFAN",
        fact: "No last-4h break. SAF claiming North Kordofan gains vs RSF; fighting reported near the Ethiopia border.",
        source: "PRESS",
        confidence: "HOLD",
        priority: "PRI-3",
        lat: 14.4,
        lon: 29.5,
      },
    ],
    markers: [
      { id: "m-iran", name: "IRAN / GULF", lat: 27.1, lon: 56.3, note: "Cape Dao + UNGA diplo", tone: "hot" },
      { id: "m-riyadh", name: "RIYADH", lat: 24.71, lon: 46.68, note: "Air-raid intercept", tone: "warn" },
      { id: "m-kkia", name: "KKIA FUEL", lat: 24.958, lon: 46.699, note: "Fuel tanks 19\u201320 Sep", tone: "hot" },
      { id: "m-wb", name: "WEST BANK", lat: 32.0, lon: 35.2, note: "Active incidents", tone: "warn" },
      { id: "m-ukr", name: "UKRAINE", lat: 48.4, lon: 35.0, note: "Kyiv daylight 23 Sep", tone: "hot" },
      { id: "m-kohat", name: "KOHAT / AFPAK", lat: 33.59, lon: 71.44, note: "Mosque + 24 Sep strikes", tone: "hot" },
      { id: "m-kandahar", name: "KANDAHAR", lat: 31.63, lon: 65.74, note: "Pak airstrike tip 24 Sep", tone: "hot" },
      { id: "m-sud", name: "SUDAN", lat: 15.5, lon: 32.5, note: "SAF / RSF", tone: "hot" },
      { id: "m-taiz", name: "TAIZ", lat: 13.58, lon: 44.02, note: "Market-strike CLAIM", tone: "warn" },
      { id: "m-madaribah", name: "AL-MADARIBAH", lat: 12.72, lon: 43.9, note: "Giants UAV CLAIM", tone: "warn" },
      { id: "m-erbil", name: "ERBIL", lat: 36.191, lon: 44.009, note: "UAV CLAIM 20 Sep", tone: "warn" },
    ],
  };
