import type { Theater } from "./sitrep.types";

export const THEATER_SUDAN: Theater =   {
    id: "sudan",
    name: "SUDAN",
    short: "SUDAN",
    status: "VISA / CEASEFIRE HOLD",
    pip: "warn",
    map: { lat: 15.5, lon: 32.0, zoom: 5.5 },
    kpis: [
      { label: "WAR", value: "SAF vs RSF", tone: "hot" },
      { label: "DARFUR", value: "EL FASHER", tone: "warn" },
      { label: "UNGA VISA", value: "BURHAN HELD", tone: "warn" },
      { label: "LAST 4H", value: "DIPLO BREAK", tone: "warn" },
    ],
    watch: [
      "Burhan visa vs Boulos 90-day ceasefire demand",
      "El Fasher / Zamzam humanitarian picture",
      "North Kordofan \u2014 verify SAF claims",
      "External pipelines (UAE / Chad / Libya / Bosaso)",
    ],
    events: [
      {
        id: "sd-visa",
        dtg: "22 SEP",
        location: "NEW YORK / PORT SUDAN",
        fact: "Reuters: US withholding Burhan UNGA visa; Sudanese/Western sources link attendance to accepting Massad Boulos 90-day ceasefire. Sudan UN ambassador letter 21 Sep asks Guterres to intervene. UN spokesperson deeply concerned.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 40.75,
        lon: -73.97,
      },
      {
        id: "sd-legit",
        dtg: "23 SEP",
        location: "NEW YORK",
        fact: "Reuters/State: spokesman Pigott says neither SAF nor RSF leaders represent legitimate constitutional governance. Sudan MFA rejects US remarks. Rubio: Sudan mediation \u201cfrustrating\u201d — commitments unmet.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 40.75,
        lon: -73.97,
      },
      {
        id: "sd-1",
        dtg: "20 SEP",
        location: "N. KORDOFAN",
        fact: "No material last-4h break. SAF still claiming North Kordofan gains vs RSF. Fighting reported near the Ethiopia border.",
        source: "PRESS",
        confidence: "HOLD",
        priority: "PRI-3",
        lat: 14.4,
        lon: 29.5,
      },
      {
        id: "sd-2",
        dtg: "07 SEP",
        location: "SUDAN",
        fact: "Control map refresh: SAF/TSC vs RSF \u201cGovernment of Peace and Unity\u201d vs SPLM-N (al-Hilu) mixed zones.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 15.5,
        lon: 32.5,
      },
      {
        id: "sd-3",
        dtg: "PRIOR",
        location: "EL FASHER",
        fact: "UN FFM: hallmarks of genocide at El-Fasher/Zamzam; up to ~2,000 former Colombian contractors with RSF; foreign drones both sides.",
        source: "UN FFM",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 13.63,
        lon: 25.35,
      },
    ],
    markers: [
      { id: "khartoum", name: "KHARTOUM", lat: 15.5, lon: 32.53, note: "Capital axis", tone: "dim" },
      { id: "elfasher", name: "EL FASHER", lat: 13.63, lon: 25.35, note: "UN FFM", tone: "hot" },
      { id: "kordofan", name: "N. KORDOFAN", lat: 14.4, lon: 29.5, note: "SAF claims", tone: "warn" },
    ],
  };
