import type { Theater } from "./sitrep.types";

export const THEATER_ENERGY: Theater =   {
    id: "energy",
    name: "ENERGY / SEA",
    short: "SEA",
    status: "TANKER WAR SURGE / FLOW DELTA",
    pip: "hot",
    map: { lat: 22.4, lon: 48.2, zoom: 5 },
    kpis: [
      { label: "HORMUZ FLOW", value: "ME CRUDE 18.3 MB/D", tone: "warn" },
      { label: "BRENT", value: "~$101.5 (6 OCT)", tone: "warn" },
      { label: "AIS COUNT", value: "0\u20135/DAY 3\u20134 OCT", tone: "hot" },
      { label: "ALT ROUTE", value: "OMAN LANE THREATENED", tone: "hot" },
    ],
    watch: [
      "Record tanker-attack week vs Kpler export rebound",
      "IRGC threat to block Oman-side \u201cillegal routes\u201d",
      "Gulf spillover: UKMTO 158-26 north of Qatar",
      "Houthi strikes on Saudi airports / Aramco (Rabigh CLAIM)",
      "Bab el-Mandeb coast fight + UKMTO 151-26",
      "Russian refining: Volgograd halt, Moscow fuel hub",
      "Second-order: LNG, fertilizer, helium, aluminum",
    ],
    events: [
      {
        id: "en-158",
        dtg: "07 OCT",
        location: "GULF / N OF QATAR",
        fact: "UKMTO 158-26 (1900Z): tanker 51 nm north of Madinat ash Shamal, Qatar, struck by multiple projectiles; casualties reported (no number); no attribution. Gulf area pin only.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 27.0,
        lon: 51.0,
      },
      {
        id: "en-cul-klang",
        dtg: "07 OCT",
        location: "S. RED SEA",
        fact: "MSCIO (via Maritime Executive 7 Oct): a containership reported shots fired by a small craft while transiting the southern Red Sea north of Bab el-Mandeb; the craft moved away, crew uninjured, ship continued northbound. Security consultants (per MarEx) identify it as Singapore-flagged CUL KLANG, operated by the Chinese CUL Lines. No claim of responsibility; MarEx notes past reports that some small boats in the region may be fishing boats protecting their nets. Sea-area pin.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 13.3,
        lon: 42.8,
      },
      {
        id: "en-week",
        dtg: "28 SEP\u201306 OCT",
        location: "HORMUZ",
        fact: "Reuters 7 Oct (three maritime security sources): at least 12 attacks on oil/LNG/LPG tankers 28 Sep\u20135 Oct, highest weekly count of the war; IMO: 9 incidents. Named hulls (Seatrade/Vanguard) incl. GHANA PROSPERITY, CAMEROON PROSPERITY, GAS VELA, MARAN GAS MYSTRAS. 6 Oct: ON PEACE struck off Musandam \u2014 India MEA (Reuters): 12 of 19 crew injured. No attribution in UKMTO notices.",
        source: "OPEN COMP",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "en-flows",
        dtg: "30 SEP\u201304 OCT",
        location: "HORMUZ",
        fact: "Kpler (via Reuters): Middle East crude exports 7-day avg 18.3 mb/d on 30 Sep, above the ~18 mb/d pre-war average. Kpler (via Iran Intl): only 5 commodity vessels crossed Hormuz Sat 3 Oct, none Sun 4 Oct (31 the prior weekend); Iran loaded zero crude in September. Export volume and transit counts do not reconcile.",
        source: "OPEN COMP",
        confidence: "DELTA",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "en-kkia-0710",
        dtg: "07 OCT",
        location: "RIYADH KKIA",
        fact: "AP: Saudi GACA \u2014 attack at King Khalid airport killed a Sudanese national, wounded 8; Houthis claimed it. Coalition spox: ballistic missile intercepted north of Riyadh. Airport pin.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 24.958,
        lon: 46.699,
      },
      {
        id: "en-rabigh",
        dtg: "05 OCT",
        location: "RABIGH",
        fact: "Reuters: Houthis say they struck an Aramco refinery at Rabigh, plus KKIA, Abha airport and Khamis Mushait base. Rabigh hit not verified; no Saudi/Aramco confirmation in sources read. Governorate pin only.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 22.799,
        lon: 39.034,
      },
      {
        id: "en-jmic-102",
        dtg: "04 OCT",
        location: "BAB EL-MANDEB / GULF OF ADEN",
        fact: "JMIC Update 102 (ICOD 04 Oct 1500 UTC): Bab el-Mandeb / Southern Red Sea and Gulf of Aden threat levels both SUBSTANTIAL; no confirmed attacks or disruptions reported in either area in the period. Bab el-Mandeb transits 01\u201303 Oct: 77 (S&P Maritime; 2023 baseline ~61/day). MT ASANA (Tanzanian flag), hijacked 17 Jul ~65 nm SW of Mukalla, still listed as hijacked. Area pin.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 12.58,
        lon: 43.33,
      },
      {
        id: "en-151",
        dtg: "04 OCT",
        location: "BAB EL-MANDEB",
        fact: "UKMTO 151-26: tanker 60 nm south of Al Mukha (Mocha) reported explosions close to the vessel; crew safe. Area pin.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 12.58,
        lon: 43.33,
      },
      {
        id: "en-volgograd",
        dtg: "02 OCT",
        location: "VOLGOGRAD",
        fact: "Reuters (industry sources): Lukoil Volgograd refinery fully halted after drone damage; Novoshakhtinsk suspended (governor, 25 Sep); Moscow refinery halted after 20 Sep attack. City pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 48.708,
        lon: 44.515,
      },
      {
        id: "en-cape-dao",
        dtg: "23 SEP",
        location: "HORMUZ / MUSANDAM",
        fact: "UKMTO + Oman MSC: CAPE DAO (Antigua/Barbuda) hit by unknown projectile ~2.5 nm off Musandam; engine-room fire; 1 crew dead, 27 evacuated. No claim of responsibility.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "en-ais-22",
        dtg: "22 SEP",
        location: "HORMUZ",
        fact: "Reuters/Kpler: commodity vessels crossing Hormuz fell to two on Monday from 10 a day earlier (AIS-visible only). Separate Marisks note: LR Stephanie and Al Maryah struck in prior incidents; responsibility unconfirmed.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "en-bessent",
        dtg: "23 SEP",
        location: "HORMUZ",
        fact: "US Treasury Secretary Bessent (Fox / Iran Intl): US forces helping move 10\u201317 million b/d through Hormuz despite tanker hits and Iran-port blockade. DELTA vs low AIS commodity counts and dark-shuttle reporting.",
        source: "STATE",
        confidence: "DELTA",
        priority: "PRI-2",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "en-marad-013",
        dtg: "23 SEP",
        location: "RED SEA / GULF OF ADEN",
        fact: "MARAD Advisory 2026-013 (effective 23 Sep 2026, expires 22 Mar 2027; cancels 2026-006): Houthis have resumed attacking commercial ships; M/Ts AMZAN and DAISY reportedly struck by Houthi missiles off Yanbu 24 Aug. Houthis declared a blockade on Saudi-affiliated shipping through Bab el-Mandeb on 20 Jul and since August have seized more Red Sea islands and west-coast territory. Israeli-, US-, UK- or Saudi-associated vessels likely at higher risk. US-flag ships strongly advised to turn off AIS unless the Master judges that unsafe. Area pin.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 12.58,
        lon: 43.33,
      },
      {
        id: "en-4",
        dtg: "20 SEP",
        location: "KAPOTNYA",
        fact: "UA strike on Gazprom Neft Moscow Oil Refinery (energy infra); AVT-6 / processing units hit; large fire reported.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.635,
        lon: 37.795,
      },
      {
        id: "en-2",
        dtg: "21 APR",
        location: "PERSIAN GULF",
        fact: "IMO: about 20,000 mariners and 2,000 ships stranded in the Gulf at peak closure.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 27,
        lon: 51,
      },
      {
        id: "en-kkia",
        dtg: "19\u201321 SEP",
        location: "RIYADH KKIA",
        fact: "Press: Houthi strike on King Khalid Airport fuel storage / jet-fuel tanks. Telegram satellite oval is CLAIM BDA, not independent confirmation of which tanks burned.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.958,
        lon: 46.699,
      },
      {
        id: "en-5",
        dtg: "21 SEP",
        location: "HORMUZ",
        fact: "UKMTO 141-26: LPG tanker outbound Hormuz hit by debris from unknown projectiles. Crew safe, no environmental impact. Press split inbound vs outbound, LPG vs oil, 0 vs 2 injured.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
    ],
    markers: [
      { id: "kapotnya-en", name: "KAPOTNYA ORF", lat: 55.635, lon: 37.795, note: "UA ORF strike", tone: "hot" },
      { id: "kkia-en", name: "KKIA FUEL", lat: 24.958, lon: 46.699, note: "Jet-fuel tanks Sep; 1 killed 7 Oct", tone: "hot" },
      { id: "hormuz2", name: "HORMUZ", lat: 26.57, lon: 56.25, note: "12 hits/wk; On Peace 6 Oct", tone: "hot" },
      { id: "bab", name: "BAB EL-MANDEB", lat: 12.58, lon: 43.33, note: "UKMTO 151-26; JMIC SUBSTANTIAL; Mocha fight", tone: "warn" },
      { id: "sred-en", name: "S. RED SEA", lat: 13.3, lon: 42.8, note: "Small-craft shots at CUL KLANG 7 Oct (MSCIO)", tone: "warn" },
      { id: "suez", name: "SUEZ", lat: 30, lon: 32.55, note: "Alt artery", tone: "dim" },
      { id: "volgograd-en", name: "VOLGOGRAD REF.", lat: 48.708, lon: 44.515, note: "Halted 2 Oct", tone: "hot" },
      { id: "rabigh", name: "RABIGH", lat: 22.799, lon: 39.034, note: "Houthi refinery CLAIM", tone: "dim" },
    ],
  };
