import type { Theater } from "./sitrep.types";

export const THEATER_LEVANT: Theater =   {
    id: "levant",
    name: "LEVANT",
    short: "LEVANT",
    status: "BURQA KILLING / GAZA STRIKES",
    pip: "hot",
    map: { lat: 32.6, lon: 35.4, zoom: 7 },
    kpis: [
      { label: "LEBANON", value: "CEASEFIRE / OCC", tone: "warn" },
      { label: "WEST BANK", value: "ACTIVE", tone: "hot" },
      { label: "GAZA", value: "STRIKES CONTINUE", tone: "warn" },
      { label: "LEBANON IDPs", value: "~330K (OCHA 5 OCT)", tone: "warn" },
    ],
    watch: [
      "West Bank settler violence (Burqa) / shooting cycle",
      "Gaza strikes vs ceasefire toll; south Lebanon buffer-zone ops",
      "Al-Eis depot blasts \u2014 cause still investigated, not attributed",
    ],
    events: [
      {
        id: "lv-burqa",
        dtg: "07 OCT",
        location: "BURQA / NABLUS",
        fact: "AFP: Palestinian health ministry \u2014 Ali al-Bazzari, 44, killed and 9 injured in Burqa, north of Nablus, in a settler attack followed by army intervention; al-Bazzari was a PA National Security Forces member. IDF: a commander \u201cneutralised\u201d a man running at him with a suspicious object. Village pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 32.299,
        lon: 35.195,
      },
      {
        id: "lv-gaza-0610",
        dtg: "06 OCT",
        location: "GAZA CITY",
        fact: "Reuters (via Al Arabiya): health officials \u2014 at least 2 killed by Israeli strikes, one near al-Shifa Hospital, Gaza City; IDF said both strikes targeted militants. Gaza health officials: at least 1,400 killed since the October ceasefire. Strip pin only.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 31.5,
        lon: 34.47,
      },
      {
        id: "lv-mansouri-op",
        dtg: "28 SEP",
        location: "MANSOURI",
        fact: "Times of Israel: IDF says it completed an operation in Mansouri (inside its south Lebanon buffer zone; residents told to evacuate ~2 months earlier), destroying 600+ Hezbollah infrastructure sites incl. 8 tunnels, plus dozens of launchers. Figures are IDF\u2019s, not independently verified. Does not corroborate the 21 Sep smoke-clip CLAIM (lv-mansouri). Town pin.",
        source: "MIL CLAIM",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.178,
        lon: 35.214,
      },
      {
        id: "lv-mansouri",
        dtg: "21 SEP",
        location: "MANSOURI / DEIR SIRYAN",
        fact: "Telegram (301 Arab World): smoke plumes over Deir Siryan and al-Mansouri, south Lebanon. Stills show distant white columns only \u2014 no munition ID. Press already had IDF fire on Mansouri; this clip is CLAIM for these two towns.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 33.178,
        lon: 35.214,
      },
      {
        id: "lv-tuffah",
        dtg: "21 SEP",
        location: "GAZA / TUFFAH",
        fact: "Telegram (301 Arab World): UAV strike in Tuffah, east Gaza City; one killed. Press TV same neighborhood: warplanes hit a residential building. Collage (night plume + later rubble) is not a building geolocation. Neighborhood pin only.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.506,
        lon: 34.466,
      },
      {
        id: "lv-shujaiyya",
        dtg: "21 SEP",
        location: "SHUJA'IYYA",
        fact: "Hebrew Telegram (@ramreports): strike on a \u2018terror target\u2019 behind the courthouse mosque, east of Shuja'iyya junction, east Gaza City. Night plume is not a geolocation. Neighborhood pin only \u2014 not the mosque.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.501,
        lon: 34.468,
      },
      {
        id: "lv-khanyounis",
        dtg: "21 SEP",
        location: "KHAN YOUNIS",
        fact: "Militant Telegram: IDF demolition in southern Khan Younis. Caption-only, no clip geolocation this pass. City-south pin \u2014 not a building.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.344,
        lon: 34.303,
      },
      {
        id: "lv-6",
        dtg: "21 SEP",
        location: "DARAA / YARMOUK",
        fact: "IDF artillery + MG fire on Wadi Abidin, Wadi al-Raqqad, outskirts of Jamla (Yarmouk Basin), western Daraa. Tip via IRNA Telegram; Anadolu/SANA/ANHA same. No casualties reported.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 32.67,
        lon: 35.88,
      },
      {
        id: "lv-3",
        dtg: "20 SEP",
        location: "JENIN",
        fact: "IDF killed a Palestinian near new Ganim outpost; claimed ramming attempt.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 32.46,
        lon: 35.3,
      },
      {
        id: "lv-khiam",
        dtg: "23 SEP",
        location: "KHIAM",
        fact: "Al-Monitor / NNA: Israeli forces carried out a series of explosions in al-Khiam (Nabatiyeh) overnight; power lines damaged; outages reported in Hasbaya, Shebaa, al-Arqoub. Material damage in Khiam and nearby towns; a Marjeyoun-area school suspended classes.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.33,
        lon: 35.61,
      },
      {
        id: "lv-5",
        dtg: "20\u201321 SEP",
        location: "ALEPPO / AL-EIS",
        fact: "Named press now corroborates ammo-depot blasts: Reuters/AFP 21 Sep \u2014 series of explosions at Syrian army weapons depot near Al-Eis, southern Aleppo countryside; 4 hurt (SANA/Emergency Ministry). Earlier 20 Sep OSINT tip (@IntelSlava) stays as lead-in. Countryside/city pin only \u2014 no depot geolocation; no attack attribution in named press.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 36.2,
        lon: 37.16,
      },
    ],
    markers: [
      { id: "sleb", name: "SOUTH LEBANON", lat: 33.2, lon: 35.3, note: "Occupation / Litani", tone: "warn" },
      { id: "mansouri", name: "MANSOURI", lat: 33.178, lon: 35.214, note: "IDF op 28 Sep; smoke CLAIM 21 Sep", tone: "warn" },
      { id: "deir-siryan", name: "DEIR SIRYAN", lat: 33.283, lon: 35.533, note: "Smoke CLAIM 21 Sep", tone: "dim" },
      { id: "jenin", name: "JENIN / GANIM", lat: 32.46, lon: 35.3, note: "Outpost incident (IDF claim)", tone: "dim" },
      { id: "gaza", name: "GAZA", lat: 31.5, lon: 34.47, note: "Strikes 6 Oct (Reuters)", tone: "warn" },
      { id: "khan-younis", name: "KHAN YOUNIS", lat: 31.344, lon: 34.303, note: "Demolition CLAIM", tone: "dim" },
      { id: "tuffah", name: "TUFFAH", lat: 31.506, lon: 34.466, note: "UAV CLAIM 21 Sep", tone: "dim" },
      { id: "shujaiyya", name: "SHUJA'IYYA", lat: 31.501, lon: 34.468, note: "Strike CLAIM 21 Sep", tone: "dim" },
      { id: "aleppo", name: "ALEPPO", lat: 36.2, lon: 37.16, note: "Al-Eis depot blasts (press)", tone: "warn" },
      { id: "khiam", name: "KHIAM", lat: 33.33, lon: 35.61, note: "IDF explosions 23 Sep", tone: "warn" },
      { id: "daraa-yarmouk", name: "DARAA / YARMOUK", lat: 32.67, lon: 35.88, note: "IDF shelling 21 Sep", tone: "warn" },
      { id: "burqa", name: "BURQA", lat: 32.299, lon: 35.195, note: "1 killed 7 Oct (AFP)", tone: "hot" },
    ],
  };
