import type { Theater } from "./sitrep.types";

export const THEATER_AFPAK: Theater =   {
    id: "afpak",
    name: "AFPAK",
    short: "AFPAK",
    status: "3RD STRIKE ROUND / CIV TOLL",
    pip: "hot",
    map: { lat: 33.5, lon: 70.5, zoom: 6 },
    kpis: [
      { label: "LATEST STRIKE", value: "30 SEP\u20131 OCT", tone: "hot" },
      { label: "CIV TOLL", value: "UNAMA: 10 KILLED", tone: "hot" },
      { label: "PAK LINE", value: "22 MILITANTS CLAIM", tone: "warn" },
      { label: "KOHAT", value: "31 DEAD", tone: "hot" },
    ],
    watch: [
      "Next Pakistani strike round vs Taliban response",
      "UNAMA civilian toll vs Pakistan\u2019s militant count",
      "ISPR Kandahar-meeting claim vs Taliban denial",
      "Kohat claim (Ittehad ul Mujahideen) vs Pakistan\u2019s TTP / Afghan link",
      "China/Turkiye/Qatar/Saudi mediation under strain",
    ],
    events: [
      {
        id: "af-strikes-0930",
        dtg: "30 SEP\u201301 OCT",
        location: "KUNAR / HELMAND",
        fact: "RFE/RL + FDD Long War Journal: Pakistani strikes overnight in Kunar (Shultan) and Helmand (Garmsir). Pakistan Info Ministry claims 22 militants killed. UNAMA: 10 civilians killed, mostly children, 9 injured. Taliban spox Mujahid: 9 killed, 11 injured. RFE/RL also reports Pakistani jet strikes on 21 and 24 Sep. Garmsir district pin \u2014 not a strike site.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 30.852,
        lon: 64.172,
      },
      {
        id: "af-ispr",
        dtg: "01 OCT",
        location: "KANDAHAR",
        fact: "FDD Long War Journal: ISPR DG claims Kandahar\u2019s governor hosted a militant meeting; Taliban\u2019s Mullah Shireen denies. City pin.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 31.63,
        lon: 65.74,
      },
      {
        id: "af-strikes-24",
        dtg: "24 SEP",
        location: "KANDAHAR / PAKTIA / KHOST",
        fact: "AJ/AFP/AP/Reuters: Pakistan says it struck 10 Afghan locations used to store/launch drones after a 23 Sep drone incursion (Info Min Tarar: deliberate/precise/proportionate). Mujahid: strikes hit Kandahar, Paktia, Khost; at least 4 dead; Taliban deny launching drones. Kandahar city pin only \u2014 not a depot.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 31.63,
        lon: 65.74,
      },
      {
        id: "af-1",
        dtg: "18\u201319 SEP",
        location: "KOHAT",
        fact: "Suicide VBIED + assault on Police Lines mosque; 20+ dead. Pakistan links attackers to Afghanistan / TTP (CLAIM on sanctuary until stronger corroboration). Update (RFE/RL, FDD LWJ): toll 31; claimed by Ittehad ul Mujahideen.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 33.59,
        lon: 71.44,
      },
      {
        id: "af-2",
        dtg: "20 SEP",
        location: "ISLAMABAD",
        fact: "Pakistan warns it will hit terrorists wherever they are. Statement REPORTED \u2014 not an airstrike report.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.68,
        lon: 73.04,
      },
      {
        id: "af-3",
        dtg: "20 SEP",
        location: "KABUL",
        fact: "Taliban warn crushing response IF Pakistan strikes; ask Saudi mediation. Statement REPORTED.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 34.53,
        lon: 69.17,
      },
      {
        id: "af-4",
        dtg: "PRIOR",
        location: "AFGHANISTAN",
        fact: "Prior major named Pakistan cross-border strike cycle: Feb\u2013Mar 2026. 24 Sep cycle now carried as af-strikes-24 (provinces named; no reconstructed track \u2014 Pak origin airbase not named).",
        source: "PRESS",
        confidence: "HOLD",
        priority: "PRI-3",
        lat: 34.53,
        lon: 69.17,
      },
    ],
    markers: [
      { id: "kohat", name: "KOHAT", lat: 33.59, lon: 71.44, note: "18 Sep attack, 31 dead", tone: "hot" },
      { id: "kandahar", name: "KANDAHAR", lat: 31.63, lon: 65.74, note: "Strikes 24 Sep; ISPR meeting CLAIM", tone: "hot" },
      { id: "islamabad", name: "ISLAMABAD", lat: 33.68, lon: 73.04, note: "10-site strike claim", tone: "hot" },
      { id: "kabul", name: "KABUL", lat: 34.53, lon: 69.17, note: "Vows appropriate response", tone: "hot" },
      { id: "garmsir", name: "GARMSIR (DIST.)", lat: 30.852, lon: 64.172, note: "Pak strike 30 Sep\u20131 Oct", tone: "hot" },
    ],
  };
