import type { Theater } from "./sitrep.types";

export const THEATER_AFPAK: Theater =   {
    id: "afpak",
    name: "AFPAK",
    short: "AFPAK",
    status: "CROSS-BORDER STRIKES",
    pip: "warn",
    map: { lat: 33.5, lon: 70.5, zoom: 6 },
    kpis: [
      { label: "KOHAT", value: "MOSQUE ATTACK", tone: "hot" },
      { label: "PAK LINE", value: "10-SITE STRIKES", tone: "hot" },
      { label: "TALIBAN", value: "VOWS RESPONSE", tone: "hot" },
      { label: "NEW AIRSTRIKE", value: "24 SEP REPORTED", tone: "hot" },
    ],
    watch: [
      "24 Sep Pak strikes — battle-damage / civilian toll corroboration",
      "Taliban \u201cappropriate response\u201d follow-through",
      "Kohat investigation \u2014 Afghan-roots / TTP claim vs Taliban denial",
      "China/Turkiye/Qatar/Saudi mediation under strain",
    ],
    events: [
      {
        id: "af-strikes-24",
        dtg: "24 SEP",
        location: "KANDAHAR / PAKTIA / KHOST",
        fact: "AJ/AFP/AP/Reuters: Pakistan says it struck 10 Afghan locations used to store/launch drones after a 23 Sep drone incursion (Info Min Tarar: deliberate/precise/proportionate). Mujahid: strikes hit Kandahar, Paktia, Khost; at least 4 dead; Taliban deny launching drones. Kandahar city pin only — not a depot.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 31.63,
        lon: 65.74,
      },
      {
        id: "af-1",
        dtg: "18\u201319 SEP",
        location: "KOHAT",
        fact: "Suicide VBIED + assault on Police Lines mosque; 20+ dead. Pakistan links attackers to Afghanistan / TTP (CLAIM on sanctuary until stronger corroboration).",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 33.59,
        lon: 71.44,
      },
      {
        id: "af-2",
        dtg: "20 SEP",
        location: "ISLAMABAD",
        fact: "Pakistan warns it will hit terrorists wherever they are. Statement REPORTED \u2014 not an airstrike report.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 33.68,
        lon: 73.04,
      },
      {
        id: "af-3",
        dtg: "20 SEP",
        location: "KABUL",
        fact: "Taliban warn crushing response IF Pakistan strikes; ask Saudi mediation. Statement REPORTED.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 34.53,
        lon: 69.17,
      },
      {
        id: "af-4",
        dtg: "PRIOR",
        location: "AFGHANISTAN",
        fact: "Prior major named Pakistan cross-border strike cycle: Feb\u2013Mar 2026. 24 Sep cycle now carried as af-strikes-24 (provinces named; no reconstructed track — Pak origin airbase not named).",
        source: "PRESS",
        confidence: "HOLD",
        priority: "PRI-3",
        lat: 34.53,
        lon: 69.17,
      },
    ],
    markers: [
      { id: "kohat", name: "KOHAT", lat: 33.59, lon: 71.44, note: "Police Lines mosque attack", tone: "hot" },
      { id: "kandahar", name: "KANDAHAR", lat: 31.63, lon: 65.74, note: "Pak airstrike tip 24 Sep", tone: "hot" },
      { id: "islamabad", name: "ISLAMABAD", lat: 33.68, lon: 73.04, note: "10-site strike claim", tone: "hot" },
      { id: "kabul", name: "KABUL", lat: 34.53, lon: 69.17, note: "Vows appropriate response", tone: "hot" },
    ],
  };
