/*
 * ETHIOPIA theater — drafted from src/theater.template.ts (COP kit, main 95e7258).
 *
 * D+ clock: D0 = 23 Sep 2026, start of the TPLF-led offensive against the federal
 * military. Source: Reuters, 4 Oct 2026 ("launched a big offensive on September 23")
 * and Reuters, 5 Oct 2026 ("The fighting since September 23 ..."). Computed with
 * python: (date(2026,10,7) - date(2026,9,23)).days == 14  ->  D+14 on 07 Oct 2026.
 * Re-compute on each refresh; do not hand-increment.
 *
 * Map centre (13.0, 39.0) = northern Ethiopia focus; theater-wide / unlocated items
 * pin there and say so in the fact text.
 */
import type { Theater } from "./sitrep.types";

export const THEATER_ETHIOPIA: Theater = {
  id: "ethiopia",
  name: "ETHIOPIA / HORN",
  short: "ETHIOPIA",
  status: "TIGRAY AIRSTRIKES / MEKELLE DELTA",
  pip: "hot",
  map: { lat: 13.0, lon: 39.0, zoom: 6 },
  kpis: [
    { label: "WAR CLOCK", value: "D+14 (23 SEP)", tone: "hot" },
    { label: "MEKELLE", value: "FELL 3\u20134 OCT / NOW DELTA", tone: "warn" },
    { label: "ERITREA TIES", value: "SEVERED 1 OCT", tone: "hot" },
    { label: "AFAR IDPs", value: "\u2265150K (PRELIM)", tone: "warn" },
  ],
  watch: [
    "Mekelle current control: Natna pullout report vs CTP advance north (DELTA)",
    "ENDF push north of Mekelle toward Adigrat / Eritrean border \u2014 Wukro/Agula CLAIM",
    "Airstrikes on TPLF-held towns: Adwa, Sheraro, Axum, Adigrat \u2014 attribution and tolls",
    "Western axis: Tekeze crossings / Mai Tsebri \u2014 road to Shire",
    "Fano vs federal supply lines: Wurgessa (A2) CLAIM, Mekane Selam (B21) fighting",
    "Eritrean troops in Tigray / Afar \u2014 unverified claims (CTP: no imagery corroboration)",
    "TPF vs Raya militia friction around Alamata \u2014 CLAIM",
    "New Alamein quad (Egypt/Eritrea/Somalia/Sudan) \u2014 Reuters: military/intel coordination pledge",
    "Oromia / OLA: alliance member since 21 Sep \u2014 no named October incident found this pass",
    "Aid access: Tigray warehouses looted; Kobo returns suspended (OCHA)",
  ],
  events: [
    {
      id: "et-mekelle",
      dtg: "03\u201304 OCT",
      location: "MEKELLE",
      fact: "Reuters 4 Oct (three sources): government forces and allied militias regained Tigray's capital; a source close to the Tigray Peace Forces says its fighters entered the centre Saturday afternoon, followed by the ENDF; humanitarian source and resident confirm. TPLF statement: regional government \u201ctemporarily moved out of Mekelle\u201d. Al Jazeera: city retaken Sunday. Reuters 5 Oct: Tigrayan forces left without a fight; shops, phone and internet returning. ENA / Al Jazeera: Abraham Belay says Addis plans an interim administration and elections within months. City pin.",
      source: "PRESS",
      confidence: "CONFIRMED",
      priority: "PRI-1",
      lat: 13.497,
      lon: 39.477,
    },
    {
      id: "et-mekelle-control",
      dtg: "05\u201306 OCT",
      location: "MEKELLE",
      fact: "Current control DELTA. Natna News 6 Oct: federal troops \u201cbegan leaving the city on Monday 5 October and are falling back eastward toward Kuiha, some nine kilometres away\u201d; government-linked Ethiopian media \u201chave still not formally confirmed\u201d the takeover. Natna names no source for the pullout beyond \u201cReports say\u201d; TPLF spox Michael Asgedom says the offensive \u201chad produced no result\u201d. Critical Threats (ISW-CTP) 6 Oct, data cutoff 6 Oct 09:00 EST: \u201cEthiopian federal forces took Mekele, the Tigray regional capital, and have since advanced north\u201d; Ethiopian Conflict Map (via CTP) says the ENDF redeployed additional forces from Mekele, presumably for further advances. City pin.",
      source: "PRESS",
      confidence: "DELTA",
      priority: "PRI-1",
      lat: 13.497,
      lon: 39.477,
    },
    {
      id: "et-adwa",
      dtg: "04\u201305 OCT",
      location: "ADWA",
      fact: "Reuters 5 Oct, citing a humanitarian bulletin: overnight airstrikes killed at least 9 in Adwa; bulletin does not say who launched them. Another aid worker confirmed Adwa strikes, no casualty figure. Reuters could not independently confirm; federal, PM-office and TPLF spokespeople did not respond. Town pin.",
      source: "PRESS",
      confidence: "REPORTED",
      priority: "PRI-1",
      lat: 14.167,
      lon: 38.891,
    },
    {
      id: "et-sheraro",
      dtg: "04\u201305 OCT",
      location: "SHERARO",
      fact: "Reuters 5 Oct, citing a humanitarian bulletin: overnight airstrikes killed at least 8 in Sheraro, northwestern Tigray; attacker not named in the bulletin. Not independently confirmed by Reuters. Town pin.",
      source: "PRESS",
      confidence: "REPORTED",
      priority: "PRI-1",
      lat: 14.393,
      lon: 37.771,
    },
    {
      id: "et-tekeze",
      dtg: "05 OCT",
      location: "MAI TSEBRI / TEKEZE",
      fact: "Reuters 5 Oct, citing a humanitarian bulletin: ENDF and Tigrayan forces exchanged heavy artillery fire close to the Tekeze River near Mai Tsebri on Monday morning. CTP 6 Oct: TDF push along the B30 into Tselemti reportedly halted 3\u20134 Oct (open-source accounts) \u2014 that part is CLAIM-level. Town pin.",
      source: "PRESS",
      confidence: "REPORTED",
      priority: "PRI-2",
      lat: 13.561,
      lon: 38.132,
    },
    {
      id: "et-mekane-selam",
      dtg: "05\u201306 OCT",
      location: "MEKANE SELAM",
      fact: "DW Amharic 6 Oct (residents): heavy fighting between government and Fano forces in and around Mekane Selam, South Wollo, from early Monday, easing after midday; a girl was killed and her parents badly wounded (resident: unclear which side's fire). Schools and trade disrupted. CTP 6 Oct: control contested, contradictory claims; Fano said to have cut the B21 here (unverified). Town pin.",
      source: "PRESS",
      confidence: "REPORTED",
      priority: "PRI-1",
      lat: 10.748,
      lon: 38.755,
    },
    {
      id: "et-wurgessa",
      dtg: "03 OCT",
      location: "WURGESSA (A2)",
      fact: "CTP 6 Oct, citing open-source mappers: Amhara Fano National Movement captured Wurgessa on the A2 highway (~30 mi south of Woldia), disrupting the federal supply road to Mekelle. ENDF and Government Communication Service have not commented; not independently verified. Town pin.",
      source: "OPEN COMP",
      confidence: "CLAIM",
      priority: "PRI-1",
      lat: 11.544,
      lon: 39.619,
    },
    {
      id: "et-wukro",
      dtg: "04 OCT",
      location: "WUKRO / AGULA",
      fact: "CTP 6 Oct, citing two open-source mappers and conflict reporter Sajid Nadeem: ENDF captured Agula and Wukro on the A2 north of Mekelle. No wire or official confirmation in sources read. Wukro town pin.",
      source: "OPEN COMP",
      confidence: "CLAIM",
      priority: "PRI-2",
      lat: 13.786,
      lon: 39.602,
    },
    {
      id: "et-alamata",
      dtg: "01\u201306 OCT",
      location: "ALAMATA",
      fact: "Addis Standard (via CTP): tensions rose between the Tigray Peace Forces and Raya militia as federal forces advanced through southern Tigray. Pro-Amhara X accounts claim fighting broke out around Alamata (1 or 3 Oct) killing several civilians and militiamen; Ethiopian Conflict Map claims Raya militia were disarmed 6 Oct. Fighting and tolls unverified. Town pin.",
      source: "OPEN COMP",
      confidence: "CLAIM",
      priority: "PRI-2",
      lat: 12.418,
      lon: 39.56,
    },
    {
      id: "et-eritrea-ties",
      dtg: "01 OCT",
      location: "ADDIS ABABA / ASMARA",
      fact: "Al Jazeera (with AFP/AP): Ethiopia MFA closes its Asmara embassy and declares 10 Eritrean diplomats persona non grata, citing Eritrean \u201chostility and belligerence\u201d; Eritrea MFA severs all diplomatic ties in response and accuses Addis of seeking Red Sea access by war. Egypt and Ethiopia expel one diplomat each. Reuters: Ethiopia accuses Eritrea, Sudan and Egypt of backing the rebels; all deny. Asmara city pin.",
      source: "STATE",
      confidence: "CONFIRMED",
      priority: "PRI-1",
      lat: 15.339,
      lon: 38.933,
    },
    {
      id: "et-eritrea-troops",
      dtg: "26 SEP\u201306 OCT",
      location: "TIGRAY / AFAR BORDER",
      fact: "Afar chief administrator Haji Awol Arba (Al Jazeera): Eritrean soldiers crossed into Afar to join the alliance offensive. UMD Media, Martin Plaut and others (via CTP) claim Eritrean forces near Irob, Rama, Sheraro, Zalambessa. CTP: no supporting media; Oct 3 satellite imagery shows no corroborating deployments. Eritrea (Yemane Gebremeskel, via Al Jazeera): Addis building a pretext to attack. US (3 Oct) and EU (5 Oct) urge both to respect territorial integrity. Theater map-centre pin \u2014 not located.",
      source: "STATE",
      confidence: "CLAIM",
      priority: "PRI-1",
      lat: 13.0,
      lon: 39.0,
    },
    {
      id: "et-alliance",
      dtg: "21\u201324 SEP",
      location: "NORTHERN ETHIOPIA",
      fact: "Global Centre for R2P / OCHA (via DONARE): seven groups incl. TPLF, Amhara Fano National Movement and OLA announced the Ethiopian Peoples' Forces Alliance for Survival on 21 Sep to overthrow the federal government. Reuters: TPLF-led offensive began 23 Sep (D0 for the clock). TPLF VP Amanuel Assefa to AFP 24 Sep: \u201cWe are in the situation of full-blown war now.\u201d AFP: TPLF seized three Tigray airports 23 Sep and attacked into Afar and Amhara. MSF (via GCR2P / OCHA-DONARE): 720+ war-wounded at its centres by late Sep. Theater map-centre pin.",
      source: "PRESS",
      confidence: "CONFIRMED",
      priority: "PRI-2",
      lat: 13.0,
      lon: 39.0,
    },
    {
      id: "et-humanitarian",
      dtg: "02\u201307 OCT",
      location: "TIGRAY / AFAR / AMHARA",
      fact: "OCHA 5 Oct: a UN agency warehouse and local/international NGO warehouses looted in Tigray (food, seed, fertiliser, pumps lost); telecoms and e-banking resumed in most of Tigray after 1+ week. OCHA 7 Oct: displacement across Central, North-Western and Eastern Tigray, no verified figures; government-led returns to Kobo suspended after security worsened. OCHA (via DONARE 2 Oct): preliminary government-led assessment finds \u2265150,000 displaced in Afar. Theater map-centre pin \u2014 region-wide.",
      source: "PRESS",
      confidence: "REPORTED",
      priority: "PRI-1",
      lat: 13.0,
      lon: 39.0,
    },
  ],
  markers: [
    { id: "et-mekelle", name: "MEKELLE", lat: 13.497, lon: 39.477, note: "Fell 3\u20134 Oct (Reuters); current control DELTA", tone: "warn" },
    { id: "et-adwa", name: "ADWA", lat: 14.167, lon: 38.891, note: "Airstrikes, \u22659 killed (aid bulletin via Reuters)", tone: "hot" },
    { id: "et-sheraro", name: "SHERARO", lat: 14.393, lon: 37.771, note: "Airstrikes, \u22658 killed (aid bulletin via Reuters)", tone: "hot" },
    { id: "et-mai-tsebri", name: "MAI TSEBRI", lat: 13.561, lon: 38.132, note: "Artillery duel at Tekeze 5 Oct", tone: "warn" },
    { id: "et-mekane-selam", name: "MEKANE SELAM", lat: 10.748, lon: 38.755, note: "Govt\u2013Fano fighting 5 Oct (DW)", tone: "warn" },
    { id: "et-wurgessa", name: "WURGESSA", lat: 11.544, lon: 39.619, note: "Fano capture CLAIM 3 Oct", tone: "dim" },
    { id: "et-wukro", name: "WUKRO", lat: 13.786, lon: 39.602, note: "ENDF capture CLAIM 4 Oct", tone: "dim" },
    { id: "et-alamata", name: "ALAMATA", lat: 12.418, lon: 39.56, note: "TPF\u2013Raya clash CLAIM", tone: "dim" },
    { id: "et-kobo", name: "KOBO", lat: 12.151, lon: 39.629, note: "IDP returns suspended (OCHA 7 Oct)", tone: "warn" },
    { id: "et-asmara", name: "ASMARA", lat: 15.339, lon: 38.933, note: "Ties severed 1 Oct", tone: "warn" },
  ],
};
