import type { Theater } from "./sitrep.types";

export const THEATER_SUDAN: Theater =   {
    id: "sudan",
    name: "SUDAN",
    short: "SUDAN",
    status: "KORDOFAN PUSH / DRONE STRIKES",
    pip: "hot",
    map: { lat: 15.5, lon: 32, zoom: 5.5 },
    kpis: [
      { label: "WAR", value: "SAF vs RSF", tone: "hot" },
      { label: "DARFUR", value: "EL FASHER", tone: "warn" },
      { label: "DIPLO", value: "BURHAN REJECTS TALKS", tone: "warn" },
      { label: "DRONE STRIKES", value: "DAMAZIN / EL OBEID", tone: "hot" },
    ],
    watch: [
      "Burhan \u201cevery inch\u201d vs Boulos Sudanese-led dialogue push",
      "SAF advance toward En Nahud / Al Khuwei (Al Jazeera)",
      "Drone strikes on cities: Damazin, El Obeid \u2014 attribution",
      "Aid convoy security \u2014 WFP Dilling\u2013Kadugli",
      "El Fasher / Zamzam humanitarian picture",
      "External pipelines (UAE / Chad / Libya / Bosaso)",
    ],
    events: [
      {
        id: "sd-damazin",
        dtg: "07 OCT",
        location: "ED DAMAZIN",
        fact: "Emergency Lawyers (AP via Al Arabiya; Daily Sabah): drone strike on Hijra neighbourhood killed at least 4 women and wounded dozens, hitting homes and a mosque; group blames RSF, RSF has not commented. IOM (Al Jazeera): 5,500+ displaced in Blue Nile over 3 days. City pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 11.807,
        lon: 34.366,
      },
      {
        id: "sd-burhan",
        dtg: "05\u201306 OCT",
        location: "MEROWE / EGYPT",
        fact: "SUNA (via Al Jazeera, Daily Sabah): Burhan, in Merowe locality, vows to retake \u201cevery inch\u201d and rejects negotiations. Reuters (via Al-Monitor): US envoy Boulos attended a Sisi-hosted lunch in Egypt with Burhan \u2014 a Sudanese official called it a \u201ccasual encounter,\u201d no talks; Boulos backs a Sudanese-led dialogue. Merowe pin.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 18.481,
        lon: 31.817,
      },
      {
        id: "sd-abu-ajal",
        dtg: "06 OCT",
        location: "EN NAHUD AREA",
        fact: "Al Jazeera: Dar Hamar Emergency Committee says an RSF attack killed 10 civilians in Abu Ajal village, southeast of En Nahud (RSF comment not seen); army advancing toward En Nahud and Al Khuwei. En Nahud town pin \u2014 not the village.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 12.692,
        lon: 28.422,
      },
      {
        id: "sd-wfp",
        dtg: "03 OCT",
        location: "DILLING / KADUGLI ROAD",
        fact: "UN News / WFP: airstrike hit two marked WFP-contracted trucks between Dilling and Kadugli, killing a driver; no attribution. Day before, a WFP truck hit an explosive device in Dilling. Dilling town pin \u2014 not the strike site.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 12.04,
        lon: 29.654,
      },
      {
        id: "sd-el-obeid",
        dtg: "30 SEP\u201301 OCT",
        location: "EL OBEID",
        fact: "AFP (via Ahram): 30 Sep drone hit a University of Kordofan dormitory, 5 killed, 47 wounded (Emergency Lawyers; no attribution); 1 Oct drone hit a shelter for displaced families, 5 killed, 13 injured (North Kordofan official blames RSF). City pin.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 13.183,
        lon: 30.223,
      },
      {
        id: "sd-visa",
        dtg: "22 SEP",
        location: "NEW YORK / PORT SUDAN",
        fact: "Reuters: US withholding Burhan UNGA visa; Sudanese/Western sources link attendance to accepting Massad Boulos 90-day ceasefire. Sudan UN ambassador letter 21 Sep asks Guterres to intervene. UN spokesperson deeply concerned.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 40.75,
        lon: -73.97,
      },
      {
        id: "sd-legit",
        dtg: "23 SEP",
        location: "NEW YORK",
        fact: "Reuters/State: spokesman Pigott says neither SAF nor RSF leaders represent legitimate constitutional governance. Sudan MFA rejects US remarks. Rubio: Sudan mediation \u201cfrustrating\u201d \u2014 commitments unmet.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 40.75,
        lon: -73.97,
      },
      {
        id: "sd-1",
        dtg: "20 SEP",
        location: "N. KORDOFAN",
        fact: "No material last-4h break. SAF still claiming North Kordofan gains vs RSF. Fighting reported near the Ethiopia border.",
        source: "PRESS",
        confidence: "HOLD",
        priority: "PRI-3",
        lat: 14.4,
        lon: 29.5,
      },
      {
        id: "sd-2",
        dtg: "07 SEP",
        location: "SUDAN",
        fact: "Control map refresh: SAF/TSC vs RSF \u201cGovernment of Peace and Unity\u201d vs SPLM-N (al-Hilu) mixed zones.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 15.5,
        lon: 32.5,
      },
      {
        id: "sd-3",
        dtg: "PRIOR",
        location: "EL FASHER",
        fact: "UN FFM: hallmarks of genocide at El-Fasher/Zamzam; up to ~2,000 former Colombian contractors with RSF; foreign drones both sides.",
        source: "UN FFM",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 13.63,
        lon: 25.35,
      },
    ],
    markers: [
      { id: "khartoum", name: "KHARTOUM", lat: 15.5, lon: 32.53, note: "Capital axis", tone: "dim" },
      { id: "elfasher", name: "EL FASHER", lat: 13.63, lon: 25.35, note: "UN FFM", tone: "hot" },
      { id: "kordofan", name: "N. KORDOFAN", lat: 14.4, lon: 29.5, note: "SAF push toward En Nahud (AJ)", tone: "warn" },
      { id: "damazin", name: "ED DAMAZIN", lat: 11.807, lon: 34.366, note: "Drone strike 7 Oct", tone: "hot" },
      { id: "el-obeid", name: "EL OBEID", lat: 13.183, lon: 30.223, note: "Drone strikes 30 Sep\u20131 Oct", tone: "hot" },
      { id: "en-nahud", name: "EN NAHUD", lat: 12.692, lon: 28.422, note: "Abu Ajal attack 6 Oct (area)", tone: "warn" },
      { id: "dilling", name: "DILLING", lat: 12.04, lon: 29.654, note: "WFP convoy hit 3 Oct", tone: "warn" },
    ],
  };
