import type { Theater } from "./sitrep.types";

export const THEATER_UKRAINE: Theater =   {
    id: "ukraine",
    name: "UKRAINE",
    short: "UKR",
    status: "KYIV DAYLIGHT + ORF",
    pip: "hot",
    map: { lat: 50.5, lon: 35.5, zoom: 5.5 },
    kpis: [
      { label: "CLOCK", value: "D+1671", tone: "dim" },
      { label: "ENERGY STRIKE", value: "MOSCOW ORF", tone: "hot" },
      { label: "DIPLO", value: "UNGA / LAVROV", tone: "warn" },
      { label: "LAST 4H", value: "KYIV DAYLIGHT", tone: "hot" },
    ],
    watch: [
      "Kyiv daylight drone toll vs overnight ballistic claims",
      "Moscow ORF damage assessment (AVT-6 / processing / isomerization)",
      "Winter energy-grid strike cycle — Zviahel fuel + Odesa warehouses",
      "Lavrov: no pause before peace deal; Rubio/Lavrov UNGA channel",
      "Pokrovsk / Donbas as HOLD",
    ],
    events: [
      {
        id: "uk-kyiv-24",
        dtg: "24 SEP",
        location: "KYIV",
        fact: "Overnight RU missiles/drones: Zelenskyy/Klitschko — Kyiv ballistic + drones; 2 dead capital; maternity-hospital area/residential/energy/logistics damaged (France24/AFP, RFE/RL). Ukr AF: Zircon, Iskander, 282 drones mainly Kyiv/Odesa. City pin only.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 50.45,
        lon: 30.52,
      },
      {
        id: "uk-chuhuiv",
        dtg: "24 SEP",
        location: "CHUHUIV DIST.",
        fact: "PM Koretsky: RU strike on farm in Chuhuiv district (SE Kharkiv) killed 6 at vegetable storage (France24/AFP). District named; pin is Chuhuiv seat only — not a warehouse geolocation.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 49.84,
        lon: 36.68,
      },

      {
        id: "uk-kyiv-23",
        dtg: "23 SEP",
        location: "KYIV",
        fact: "AP: Russian daylight drone barrage on Kyiv kills 2, wounds 41 ahead of Zelenskyy UNGA address. Fires; damage to rail, warehouses, fuel sites reported. MoD Russia claims strikes on military-industrial/energy/logistics.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 50.45,
        lon: 30.52,
      },
      {
        id: "uk-lavrov",
        dtg: "23 SEP",
        location: "NEW YORK",
        fact: "AP: Lavrov tells UN channel Moscow is open to talks but will not accept a break in hostilities before a peace deal. Met Rubio on UNGA sidelines; Rubio says Trump invited Putin to December G20 in Miami.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 40.75,
        lon: -73.97,
      },
            {
        id: "uk-kap",
        dtg: "20 SEP",
        location: "KAPOTNYA",
        fact: "Gazprom Neft Moscow ORF hit (AVT-6 etc); Zelensky/Gen Staff confirm; Reuters: 2 dead Moscow region.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.635,
        lon: 37.795,
      },
      {
        id: "uk-wave",
        dtg: "20 SEP",
        location: "MOSCOW",
        fact: "Sobyanin: largest drone attack; 1600+ downed claim / 450 toward Moscow.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.75,
        lon: 37.62,
      },
{
        id: "uk-1",
        dtg: "20 SEP",
        location: "KYIV",
        fact: "Witkoff still talking a \u201cgood resolution\u201d after Kyiv; pushing trilateral talks. No deal text.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-3",
        lat: 50.45,
        lon: 30.52,
      },
      {
        id: "uk-2",
        dtg: "20 SEP",
        location: "WARSAW",
        fact: "Tusk: Moscow will not talk without Ukraine\u2019s \u201ctotal capitulation\u201d; winter to be made \u201ctragically critical.\u201d",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-3",
        lat: 52.23,
        lon: 21.01,
      },
      {
        id: "uk-3",
        dtg: "20 SEP",
        location: "DONBAS",
        fact: "Kyiv denounces Russian Duma vote being run in illegally annexed oblasts. Zelenskyy eastern-Europe huddle through Sunday.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-3",
        lat: 48.0,
        lon: 37.8,
      },
      {
        id: "uk-4",
        dtg: "21 SEP",
        location: "ZVIAHEL",
        fact: "Zhytomyr OVA / Ukrinform: Russian strike on a gas station on the M-06 Kyiv–Chop highway near Zviahel. Twice this morning; traffic restrictions later lifted.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 50.59,
        lon: 27.61,
      },
      {
        id: "uk-5",
        dtg: "21 SEP",
        location: "ZAPORIZHZHIA",
        fact: "Ukrainian officials / Zelenskyy: drones damaged a shopping center and Zaporizhzhia National University’s oldest building. Injury counts differ across press.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 47.84,
        lon: 35.14,
      },
      {
        id: "uk-6",
        dtg: "21 SEP",
        location: "ODESA",
        fact: "SES / Odesa OVA: warehouse fires after overnight strikes. Telegram named Silpo; officials said supermarket-chain warehouses, no casualties.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 46.48,
        lon: 30.73,
      },
      {
        id: "uk-7",
        dtg: "21 SEP",
        location: "KHARKIV",
        fact: "OSINT (@war_cube / JHArnous): geolocated strike on Epicentr, Kharkiv 49.908390, 36.275573. Stills show ISR reticle + blurred aftermath overlay. Site name not independently confirmed here.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 49.90839,
        lon: 36.275573,
      },
      {
        id: "uk-8",
        dtg: "21 SEP",
        location: "ODESA",
        fact: "OSINT (@war_cube / JHArnous): unknown warehouse hit at 46.524836, 30.602931. Aligns with SES/OVA warehouse-fire reporting; specific building is a geolocation CLAIM.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 46.524836,
        lon: 30.602931,
      },
      {
        id: "uk-9",
        dtg: "21 SEP",
        location: "NOVOALEKSANDROVKA",
        fact: "RV voenkor map: 128 OMSBr took Novoaleksandrovka (Vovchansk raion) from Ukraine’s 129th. Single-source MIL CLAIM — no independent confirmation in this pass. Village pin only, no control-line.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 50.15739,
        lon: 37.24777,
      },
      {
        id: "uk-10",
        dtg: "21 SEP",
        location: "POLNAYA",
        fact: "RV voenkor map: 82 MSP took Polnaya after 57th OMBr. Same single-source claim as Novoaleksandrovka. Village pin only.",
        source: "MIL CLAIM",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 50.16157,
        lon: 36.98636,
      },
    ],
    markers: [
      { id: "kapotnya", name: "KAPOTNYA ORF", lat: 55.635, lon: 37.795, note: "ORF hit / fire", tone: "hot" },
      { id: "moscow", name: "MOSCOW", lat: 55.75, lon: 37.62, note: "Mass drone wave", tone: "hot" },
      { id: "kyiv", name: "KYIV", lat: 50.45, lon: 30.52, note: "Daylight drones 23 Sep", tone: "hot" },
      { id: "pokrovsk", name: "POKROVSK AXIS", lat: 48.28, lon: 37.18, note: "HOLD", tone: "warn" },
      { id: "blacksea", name: "BLACK SEA", lat: 45.3, lon: 32.5, note: "Energy / maritime", tone: "dim" },
      { id: "zviahel", name: "ZVIAHEL", lat: 50.59, lon: 27.61, note: "M-06 fuel strike 21 Sep", tone: "hot" },
      { id: "zaporizhzhia", name: "ZAPORIZHZHIA", lat: 47.84, lon: 35.14, note: "Mall / ZNU drones", tone: "warn" },
      { id: "odesa", name: "ODESA", lat: 46.48, lon: 30.73, note: "Warehouse fires (OVA)", tone: "warn" },
      { id: "kharkiv-epicentr", name: "KHARKIV EPICENTR", lat: 49.90839, lon: 36.275573, note: "OSINT geoloc CLAIM", tone: "warn" },
      { id: "odesa-wh", name: "ODESA WAREHOUSE", lat: 46.524836, lon: 30.602931, note: "OSINT geoloc CLAIM", tone: "warn" },
      { id: "novoaleks", name: "NOVOALEKSANDROVKA", lat: 50.15739, lon: 37.24777, note: "RV capture CLAIM", tone: "warn" },
      { id: "polnaya", name: "POLNAYA", lat: 50.16157, lon: 36.98636, note: "RV capture CLAIM", tone: "warn" },
      { id: "chuhuiv", name: "CHUHUIV DIST.", lat: 49.84, lon: 36.68, note: "Farm strike 6 dead 24 Sep", tone: "hot" },
    ],
  };
