/*
 * YEMEN theater — drafted from src/theater.template.ts (COP kit, main 95e7258).
 * Moved from sitrep.levant.ts: lv-aden, lv-saudi-air, lv-mocha, lv-turbah, lv-taiz,
 * lv-madaribah (now yem-*). Moved CLAIMs keep CLAIM. No D+ clock: no single clean,
 * sourced start date for this round of fighting.
 * One theater per item: maritime advisories / shipping incidents (UKMTO, JMIC, MARAD,
 * MSCIO) and the KKIA strikes live in sitrep.energy.ts, not here.
 */
import type { Theater } from "./sitrep.types";

export const THEATER_YEMEN: Theater = {
  id: "yemen",
  name: "YEMEN / RED SEA",
  short: "YEMEN",
  status: "DAWN OF YEMEN / DHUBAB FIGHT",
  pip: "hot",
  map: { lat: 15.0, lon: 44.0, zoom: 6 },
  kpis: [
    { label: "WEST COAST", value: "MOCHA DELTA / DHUBAB", tone: "hot" },
    { label: "HOUTHI\u2192KSA", value: "AIRPORTS HIT (GACA)", tone: "hot" },
    { label: "DISPLACED", value: "201K (IOM 7 OCT)", tone: "warn" },
    { label: "COALITION AIR", value: "100 JETS (COALITION)", tone: "warn" },
  ],
  watch: [
    "Mocha / Dhubab / Bab el-Mandeb control \u2014 govt vs Houthi claims (DELTA); JMIC still lists Houthi control",
    "Al-Waziiya / Jabal Habashi mountain push \u2014 shaping op for the coast (CTP-ISW)",
    "Taiz encirclement \u2014 al-Turbah / Taiz\u2013Aden road",
    "Houthi strikes on Aden and Saudi airports (Abha, Jazan, Najran); KKIA/Rabigh tracked in Energy",
    "Houthi \u201cban\u201d warning to airlines over Saudi airspace (Saree, via CTP-ISW) \u2014 CLAIM/threat",
    "Saudi naval strikes on Hudaydah coast; Houthi response vs Saudi navy (shipping incidents tracked in Energy)",
    "Mecca Joint Defence Agreement \u2014 Turkish/Pakistani deployments to KSA; Syria weighing aid (Reuters)",
    "Taiz market-strike CLAIM \u2014 city pin only, no site geolocation",
    "Al-Madaribah Giants UAV CLAIM \u2014 district pin only, no pickup geolocation",
  ],
  events: [
    {
      id: "yem-aden",
      dtg: "07 OCT",
      location: "ADEN",
      fact: "Yemen Transport Ministry (Al Jazeera/Reuters): at least two ballistic missiles plus drones targeted Aden airport runway/terminal; one landed near the runway minutes before a Cairo flight (ministry: diverted to Jeddah; AP/FlightAware: Flight 603 landed 03:30). Aden security (AP): no casualties. Houthis say they targeted \u201cSaudi military supplies\u201d at Badr camp near the airport. City pin.",
      source: "PRESS",
      confidence: "CONFIRMED",
      priority: "PRI-1",
      lat: 12.79,
      lon: 45.029,
    },
    {
      id: "yem-saudi-air",
      dtg: "06\u201307 OCT",
      location: "ABHA",
      fact: "AP 7 Oct: Saudi GACA \u2014 attack on Abha airport killed Moroccan and Algerian residents and wounded 28; Houthis claimed it. (The same GACA statement's King Khalid airport attack is carried in Energy, en-kkia-0710.) Reuters 5 Oct: Saudi Arabia, Turkey and Pakistan agree to rapidly deploy forces in KSA under the Mecca Joint Defence Agreement. Abha city pin.",
      source: "PRESS",
      confidence: "CONFIRMED",
      priority: "PRI-1",
      lat: 18.216,
      lon: 42.504,
    },
    {
      id: "yem-dhubab",
      dtg: "06\u201307 OCT",
      location: "DHUBAB",
      fact: "AP 7 Oct: fighting centred in and around Dhubab, ~54 km south of Mokha, per both the Houthis and the government. Reuters 7 Oct: pro-govt forces attempting an advance in hills east of the coastal plain (Yemeni military/govt sources); Houthis claim attacks repelled. CTP-ISW 6 Oct (citing two Yemen analysts): no govt gains north of Dhubab Airport since it was seized; Houthi ballistic-missile attack on govt forces near Ras al-Ara 6 Oct is CLAIM-level (Houthi channel + one analyst, via CTP-ISW). Town pin.",
      source: "PRESS",
      confidence: "CONFIRMED",
      priority: "PRI-1",
      lat: 12.943,
      lon: 43.411,
    },
    {
      id: "yem-mocha",
      dtg: "05\u201307 OCT",
      location: "MOCHA / DHUBAB",
      fact: "Reuters 5 Oct: govt says Saudi-backed forces retook the coast around Bab el-Mandeb up to Mocha and Defence Ministry says Mocha fell (Reuters could not verify; Houthis: baseless); Dhubab airstrip taken. AFP 6 Oct: military sources say Mocha supply route cut, capture not confirmed; Giants Brigades report a \u201ctight siege.\u201d AP 7 Oct: two Houthi officials claim they regained Dhubab and Bab el-Mandeb; govt official denies. Reuters 7 Oct: govt Mocha claim \u201cpremature\u201d per Yemeni military officials and analysts. JMIC 4 Oct: Houthis still hold Mocha, Dhubab, Perim, Zuqar, Hanish. Control DELTA. Town pin.",
      source: "PRESS",
      confidence: "DELTA",
      priority: "PRI-1",
      lat: 13.318,
      lon: 43.25,
    },
    {
      id: "yem-waziyah",
      dtg: "06\u201307 OCT",
      location: "AL-WAZIIYA (TAIZ)",
      fact: "Al Jazeera / Anadolu / CTP-ISW: Yemeni army media says Homeland (Nation's) Shield Forces began a \u201clarge-scale operation\u201d to retake al-Waziiya district, west of Taiz city and east of Mocha. Army media claims strategic hills over al-Mansoura amid a Houthi \u201cmass retreat\u201d; Houthis say they repelled it. CTP-ISW: advances limited so far. Gains are CLAIM; the offensive itself is reported. District pin \u2014 not a front line.",
      source: "PRESS",
      confidence: "REPORTED",
      priority: "PRI-1",
      lat: 13.174,
      lon: 43.73,
    },
    {
      id: "yem-habashi",
      dtg: "06 OCT",
      location: "JABAL HABASHI (TAIZ)",
      fact: "Nation's Shield Forces on X (via Anadolu): troops captured the highest peak in Jabal Habashi district; no details, no immediate Houthi comment. Single-party claim. Taiz city pin \u2014 not the peak.",
      source: "MIL CLAIM",
      confidence: "CLAIM",
      priority: "PRI-2",
      lat: 13.575,
      lon: 44.022,
    },
    {
      id: "yem-dawn",
      dtg: "04\u201306 OCT",
      location: "YEMEN",
      fact: "Al Jazeera / Anadolu: PLC chairman Rashad al-Alimi announced \u201cDawn of Yemen\u201d to retake all Houthi-held territory incl. Sanaa (AJ: Sunday; Anadolu: Monday). AP / Al Jazeera: coalition says 100 fighter jets are supporting; spox al-Malki vows \u201cfull operational support\u201d until the Houthis are \u201celiminated\u201d. AP: officials say US support includes intelligence sharing, target identification and planning. Theater map-centre pin \u2014 not located.",
      source: "PRESS",
      confidence: "CONFIRMED",
      priority: "PRI-1",
      lat: 15.0,
      lon: 44.0,
    },
    {
      id: "yem-turbah",
      dtg: "04\u201305 OCT",
      location: "TAIZ / AL-TURBAH",
      fact: "Reuters 5 Oct (govt military sources): Houthis advanced near Taiz (al-Turbah, al-Mawasit) and damaged a culvert on the Taiz\u2013Aden road; sources say Taiz is surrounded (one denies). AP: govt counteroffensive began after rebels seized Turbah. UN (AP): ~1,000 killed, 200k+ displaced; IOM (Reuters): 184k displaced. Town pin.",
      source: "PRESS",
      confidence: "REPORTED",
      priority: "PRI-1",
      lat: 13.213,
      lon: 44.124,
    },
    {
      id: "yem-jazan-najran",
      dtg: "05\u201306 OCT",
      location: "JAZAN / NAJRAN",
      fact: "Al Jazeera: Saudi GACA says King Abdullah bin Abdulaziz airport (Jazan) and Najran airport were hit, wounding 3 with material damage. Houthi spox Saree (via CTP-ISW) claimed strikes on Jizan and Najran targets among 7+ Saudi sites on 5 Oct. Jazan city pin.",
      source: "PRESS",
      confidence: "REPORTED",
      priority: "PRI-1",
      lat: 16.895,
      lon: 42.558,
    },
    {
      id: "yem-khamis",
      dtg: "06 OCT",
      location: "KHAMIS MUSHAIT",
      fact: "Al Jazeera: coalition spox al-Maliki says a Houthi ballistic missile aimed at Khamis Mushait was intercepted and destroyed, and that missile threats originate from Sanaa, Saada and Amran. Houthis (Saree, via CTP-ISW/AP) claim attacks on King Khalid Air Base there. No damage reported in sources read. City pin.",
      source: "STATE",
      confidence: "REPORTED",
      priority: "PRI-2",
      lat: 18.3,
      lon: 42.733,
    },
    {
      id: "yem-hudaydah-naval",
      dtg: "05 OCT",
      location: "HODEIDAH COAST",
      fact: "Saudi Joint Force Command (SPA, via CTP-ISW): first Saudi naval bombardment of the conflict hit Houthi weapons depots, explosive fast-attack-craft stores and naval mines on the Hudaydah coast, pre-empting an \u201cimminent\u201d attack on shipping. Yemeni media (via CTP-ISW): Saudi strikes on Kamaran Island and al-Salif port. Effects not independently verified. Hodeidah city pin \u2014 not the targets.",
      source: "MIL CLAIM",
      confidence: "CLAIM",
      priority: "PRI-2",
      lat: 14.798,
      lon: 42.954,
    },
    {
      id: "yem-humanitarian",
      dtg: "05\u201307 OCT",
      location: "YEMEN",
      fact: "IOM (Reuters / Al Jazeera 7 Oct): 201,217 displaced, up from 76,000 mid-Sep. UN (AP): almost 1,000 killed in the latest fighting. OHCHR (via OCHA 5 Oct): at least 46 civilians killed since start of August, 24 of them children, 130+ injured. WHO (AP): cholera and malnutrition rising, surgical-supply shortages. Both sides claim hundreds killed without details (Reuters). Theater map-centre pin \u2014 not located.",
      source: "PRESS",
      confidence: "REPORTED",
      priority: "PRI-1",
      lat: 15.0,
      lon: 44.0,
    },
    {
      id: "yem-taiz-market",
      dtg: "21 SEP",
      location: "TAIZ",
      fact: "Houthi-aligned Telegram (@sarzaminkhanjarha): Saudi strike on a local market in Taiz. Clip: outdoor gathering + fireball, camera overlay. Unverified attribution/site. City pin only \u2014 no market geolocation.",
      source: "MIL CLAIM",
      confidence: "CLAIM",
      priority: "PRI-2",
      lat: 13.58,
      lon: 44.02,
    },
    {
      id: "yem-madaribah",
      dtg: "21 SEP",
      location: "AL-MADARIBAH",
      fact: "Hebrew Telegram (Hananel Aviv): Southern Giants claim UAV hits on Houthi cells and military pickups on the Al-Wazia\u2013Al-Madaribah front, west Lahij near Bab al-Mandeb. Clip not independently geolocated. District pin only \u2014 not a vehicle, not a control-line. Arab News 20 Sep: Nation\u2019s Shield / Giants fighting and a drone downed near Kahboub Mountain in Al-Madaribah Wa Al-Aarah \u2014 related district fight, not this clip.",
      source: "MIL CLAIM",
      confidence: "CLAIM",
      priority: "PRI-2",
      lat: 12.72,
      lon: 43.9,
    },
  ],
  markers: [
    { id: "yem-aden", name: "ADEN", lat: 12.79, lon: 45.029, note: "Airport missile/drone attack 7 Oct", tone: "hot" },
    { id: "yem-mocha", name: "MOCHA", lat: 13.318, lon: 43.25, note: "Control DELTA; JMIC: Houthi-held", tone: "warn" },
    { id: "yem-dhubab", name: "DHUBAB", lat: 12.943, lon: 43.411, note: "Main fighting 6\u20137 Oct (AP/Reuters)", tone: "hot" },
    { id: "yem-waziyah", name: "AL-WAZIIYA", lat: 13.174, lon: 43.73, note: "Govt offensive 6 Oct; gains CLAIM", tone: "warn" },
    { id: "yem-taiz", name: "TAIZ", lat: 13.58, lon: 44.02, note: "Encirclement (Reuters); market + Habashi CLAIMs", tone: "warn" },
    { id: "yem-turbah", name: "AL-TURBAH", lat: 13.213, lon: 44.124, note: "Houthi advance / Taiz road cut", tone: "warn" },
    { id: "yem-madaribah", name: "AL-MADARIBAH", lat: 12.72, lon: 43.9, note: "Giants UAV CLAIM 21 Sep", tone: "dim" },
    { id: "yem-hodeidah", name: "HODEIDAH", lat: 14.798, lon: 42.954, note: "Saudi naval strike CLAIM 5 Oct", tone: "dim" },
    { id: "yem-abha", name: "ABHA", lat: 18.216, lon: 42.504, note: "Airport attack, deaths (GACA)", tone: "hot" },
    { id: "yem-jazan", name: "JAZAN", lat: 16.895, lon: 42.558, note: "Airport hit, 3 hurt w/ Najran (GACA)", tone: "warn" },
    { id: "yem-najran", name: "NAJRAN", lat: 17.544, lon: 44.225, note: "Airport hit (GACA)", tone: "warn" },
    { id: "yem-khamis", name: "KHAMIS MUSHAIT", lat: 18.3, lon: 42.733, note: "Missile intercepted 6 Oct (coalition)", tone: "warn" },
  ],
};
