import type { Theater } from "./sitrep.types";

export const THEATER_IRAN: Theater =   {
    id: "iran",
    name: "IRAN / GULF",
    short: "GULF",
    status: "UNGA DIPLO / HORMUZ HIT",
    pip: "hot",
    map: { lat: 26.6, lon: 55.2, zoom: 6 },
    kpis: [
      { label: "CONFLICT CLOCK", value: "D+208", tone: "hot" },
      { label: "HORMUZ", value: "CAPE DAO HIT", tone: "hot" },
      { label: "DIPLO", value: "UNGA / QATAR", tone: "warn" },
      { label: "NEXT MOVE", value: "CONDITIONS CLOCK", tone: "hot" },
    ],
    watch: [
      "Rezaei 4\u20135-day conditions vs actual Hormuz reopen",
      "Cape Dao attribution — still unknown projectile",
      "US resume-strikes claim vs actual sortie generation",
      "Qatar-passed conditions / NY shuttle follow-through",
    ],
    events: [
      {
        id: "ir-cape-dao",
        dtg: "23 SEP",
        location: "HORMUZ / MUSANDAM",
        fact: "UKMTO + Oman: Antigua/Barbuda-flagged CAPE DAO hit by unknown projectile ~2.5 nm off Musandam; engine-room fire; 1 dead, 27 evacuated. No responsibility claim.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ir-unga",
        dtg: "22\u201323 SEP",
        location: "NEW YORK",
        fact: "Reuters: first known indirect US\u2013Iran talks since July ceasefire collapse (Araqchi via Qatar with Witkoff/Kushner). Pezeshkian UNGA rejects surrender; senior official says sides still far apart on ending the war.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 40.75,
        lon: -73.97,
      },
      {
        id: "ir-hormuz-offer",
        dtg: "22 SEP",
        location: "TEHRAN",
        fact: "Reuters exclusive: senior Iranian official — Iran can reopen Hormuz within seven days if US eases military pressure and lifts blockade on Iranian ports. Proposal previously passed via mediators 16 Sep.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 35.69,
        lon: 51.39,
      },
      {
        id: "ir-rezaei",
        dtg: "23 SEP",
        location: "TEHRAN",
        fact: "SNSC secretary Rezaei on state TV (Iran Intl): US given 4\u20135 days to meet Iran\u2019s conditions; until accepted, no negotiations and Hormuz will not be reopened. STATE messaging.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-1",
        lat: 35.69,
        lon: 51.39,
      },
            {
        id: "ir-trend",
        dtg: "18 SEP",
        location: "HORMUZ",
        fact: "IRGC claim: tanker Trend detained in Hormuz. Confidence CLAIM only \u2014 state narrative, not independently confirmed.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 26.57,
        lon: 56.25,
      },
{
        id: "ir-1",
        dtg: "20 SEP",
        location: "TEHRAN",
        fact: "Tehran (state): intel that the US, with some regional backing, is prepping to resume strikes.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-1",
        lat: 35.69,
        lon: 51.39,
      },
      {
        id: "ir-2",
        dtg: "20 SEP",
        location: "TEHRAN",
        fact: "Ghalibaf: \u201cdevastating blows\u201d first, talks later. SNSC Rezaei: conditions already sent to Washington via Qatar.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-1",
        lat: 35.7,
        lon: 51.4,
      },
      {
        id: "ir-3",
        dtg: "16 SEP",
        location: "HORMUZ",
        fact: "US military: Hormuz \u201ckept open.\u201d Tracking / press: shipping at new lows.",
        source: "MIL CLAIM",
        confidence: "DELTA",
        priority: "PRI-2",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ir-7",
        dtg: "21 SEP",
        location: "HORMUZ",
        fact: "UKMTO 141-26 ATTACK, 1330Z: LPG tanker outbound Hormuz hit by debris from unknown projectiles. Crew safe, no spill, proceeding. Press split inbound/oil/2 injured.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ir-erbil",
        dtg: "20 SEP",
        location: "ERBIL",
        fact: "Hebrew Telegram (News_il_h): UAV near US consulate, Erbil. Same-day Greek press: drone downed near Erbil airport / coalition presence; Reuters/AFP cited on intercept. Smoke still is not a site geolocation. City pin \u2014 consulate vs airport DELTA.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 36.191,
        lon: 44.009,
      },
      {
        id: "ir-4",
        dtg: "13 SEP",
        location: "QESHM",
        fact: "Iranian cargo struck off Qeshm. State media: 1 killed, 4 wounded. Neighbor brief postponed.",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.76,
        lon: 55.8,
      },
      {
        id: "ir-5",
        dtg: "08 SEP",
        location: "BANDAR ABBAS",
        fact: "Iran: MQ-1 Predator downed over Bandar Abbas. IRGC: seized US-made Dive-LD UUV at Hormuz entrance.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 27.18,
        lon: 56.27,
      },
      {
        id: "ir-6",
        dtg: "28 FEB",
        location: "HORMUZ",
        fact: "US\u2013Israel air war opens. IRGC moves to choke Hormuz. Pre-war: ~25% seaborne oil / ~20% LNG.",
        source: "OPEN COMP",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 26.6,
        lon: 56.3,
      },
    ],
    markers: [
      { id: "hormuz", name: "HORMUZ", lat: 26.57, lon: 56.25, note: "Cape Dao hit 23 Sep", tone: "hot" },
      { id: "qeshm", name: "QESHM", lat: 26.76, lon: 55.8, note: "Cargo strike 13 Sep", tone: "warn" },
      { id: "babb", name: "BANDAR ABBAS", lat: 27.18, lon: 56.27, note: "UAS / UUV claims", tone: "warn" },
      { id: "tehran", name: "TEHRAN", lat: 35.69, lon: 51.39, note: "Hormuz conditions / UNGA", tone: "hot" },
      { id: "erbil", name: "ERBIL", lat: 36.191, lon: 44.009, note: "UAV CLAIM 20 Sep", tone: "warn" },
    ],
  };
