import type { Theater } from "./sitrep.types";

export const THEATER_IRAN: Theater =   {
    id: "iran",
    name: "IRAN / GULF",
    short: "GULF",
    status: "TANKER WAR SURGE / DIPLO STALL",
    pip: "hot",
    map: { lat: 26.6, lon: 55.2, zoom: 6 },
    kpis: [
      { label: "CONFLICT CLOCK", value: "D+221", tone: "hot" },
      { label: "HORMUZ", value: "12 HITS / WK", tone: "hot" },
      { label: "DIPLO", value: "QATAR / 7 CONDITIONS", tone: "warn" },
      { label: "NEXT MOVE", value: "US BUILDUP / NOV", tone: "hot" },
    ],
    watch: [
      "UKMTO 158-26 N of Qatar \u2014 attribution / Gulf spillover",
      "Naqdi threat to block Oman-side \u201cillegal routes\u201d",
      "Qatar relay vs Ghalibaf\u2019s seven conditions; enrichment \u201cred line\u201d",
      "3rd CSG / MEU flow vs Trump post-midterm strike talk",
      "Sirik / Kuhestak / Qeshm blast reports \u2014 state media only",
      "Cape Dao / On Peace attribution \u2014 no claim yet",
    ],
    events: [
      {
        id: "ir-158",
        dtg: "07 OCT",
        location: "GULF / N OF QATAR",
        fact: "UKMTO 158-26 (1900Z): tanker 51 nm north of Madinat ash Shamal, Qatar, reported struck by multiple projectiles; casualties reported (no number given); no attribution in the notice. Gulf area pin only \u2014 not the vessel position.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 27.0,
        lon: 51.0,
      },
      {
        id: "ir-naqdi",
        dtg: "07 OCT",
        location: "TEHRAN",
        fact: "Reuters (citing Fars): IRGC commander\u2019s adviser Naqdi says Hormuz is \u201cclosed\u201d and under full control until Iran\u2019s demands are met, and \u201cillegal routes\u201d on the Oman-side southern pathway will be blocked soon. Army spox Akraminia (IRNA via Euronews): forces ready for pre-emptive operations. Senior official to Reuters (via Iran Intl): right to enrich is a \u201cred line.\u201d",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 35.69,
        lon: 51.39,
      },
      {
        id: "ir-kuhestak",
        dtg: "04\u201307 OCT",
        location: "SIRIK / KUHESTAK",
        fact: "Iranian state media only: Fars (via Iran Intl, 7 Oct) \u2014 two explosions with a strong shock wave heard from the sea near Kuhestak, Sirik county; cause not determined (Fars speculated warning shots at \u201cviolating vessels\u201d). IRNA/Fars (via IranWire) reported blasts from the sea near Qeshm and Sirik on 4 Oct; IRNA a blast sound near Qeshm 6 Oct. No independent corroboration. Town pin only.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 26.802,
        lon: 57.026,
      },
      {
        id: "ir-on-peace",
        dtg: "06 OCT",
        location: "HORMUZ / MUSANDAM",
        fact: "Panama-flagged tanker ON PEACE struck ~9 nm off Limah, Musandam; fire on board. Oman MoD (Al Jazeera/AFP): air force evacuated 10 crew to Khasab hospital. India MEA (Reuters): 12 of 19 crew injured, 11 of them Indian. No claim of responsibility. Strait area pin.",
        source: "PRESS",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ir-week",
        dtg: "28 SEP\u201305 OCT",
        location: "HORMUZ",
        fact: "Reuters 7 Oct (three maritime security sources): at least 12 attacks on oil/LNG/LPG tankers in the week \u2014 highest weekly count since the war began; IMO counted 9 incidents. UKMTO 147\u2013157-26 (2\u20135 Oct): hits, fires, a drone into a funnel/engine room, propulsion losses; UKMTO 152-26: IRGC hailed an inbound tanker 11 nm N of Khasab and ordered it back (complied). JMIC: Iran asserting presence. UKMTO notices name no attacker.",
        source: "OPEN COMP",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ir-qatar",
        dtg: "04\u201306 OCT",
        location: "DOHA",
        fact: "Ghalibaf (Reuters via Al Arabiya, 4 Oct): Hormuz stays shut until seven conditions under the June Islamabad MoU are met; US answered Iran\u2019s 7-day proposal via Qatari intermediaries. Qatar MFA spox Al-Hashmi (6 Oct): indirect talks and message exchanges continue via Qatar and partners; Interior Minister Momeni met the Emir in Doha and carried back the latest proposal (Washington Times).",
        source: "STATE",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 25.286,
        lon: 51.526,
      },
      {
        id: "ir-us-track",
        dtg: "26 SEP\u201306 OCT",
        location: "WASHINGTON",
        fact: "Trump 26 Sep (Guardian/Reuters/AP): \u201cThey made a proposal but I reject it.\u201d WSJ via Stars and Stripes (2 Oct): third carrier strike group + MEU, ~9\u201310k personnel, by end-November; USS Theodore Roosevelt deployed, Makin Island ARG left San Diego. Trump to Time: strikes \u201cpossible\u201d after the midterms. Vance to Reuters (5 Oct): deal needs something \u201cmeaningful on their enrichment capacity.\u201d Trump 6 Oct: \u201cthe nice way or the not-so-nice way.\u201d",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 38.895,
        lon: -77.036,
      },
      {
        id: "ir-iraq-exit",
        dtg: "30 SEP",
        location: "ERBIL",
        fact: "Pentagon spox Parnell (Al Jazeera; CENTCOM): final US/coalition troops departed Erbil Air Base; OIR mission in Iraq ended, task force relocated to Jordan. Trump hailed the exit. City pin only.",
        source: "STATE",
        confidence: "CONFIRMED",
        priority: "PRI-2",
        lat: 36.191,
        lon: 44.009,
      },
      {
        id: "ir-koya",
        dtg: "28 SEP",
        location: "KOYA",
        fact: "KRG Security Agency (Kurdistan24): three drones targeted the Azadi camp in Koya 01:40\u201302:10, no casualties. KDPI senior official (Rudaw) blamed Iran \u2014 attribution is a party CLAIM; Tehran comment not seen. Separate from the 20 Sep Erbil CLAIM. Town pin only.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 36.085,
        lon: 44.628,
      },
      {
        id: "ir-sirik",
        dtg: "06 OCT",
        location: "SIRIK",
        fact: "Telegram (@FotrosResistancee): locals report explosion sounds heard in Sirik (Hormozgan, Gulf of Oman coast). Single-source; no IRNA/Tasnim/Fars/UKMTO/wire corroboration for Sirik this cycle. Same evening IRNA (via Iran Intl) reported a blast sound from the sea near Qeshm \u2014 not Sirik-specific. Town pin only.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 26.518,
        lon: 57.102,
      },
      {
        id: "ir-cape-dao",
        dtg: "23 SEP",
        location: "HORMUZ / MUSANDAM",
        fact: "UKMTO + Oman: Antigua/Barbuda-flagged CAPE DAO hit by unknown projectile ~2.5 nm off Musandam; engine-room fire; 1 dead, 27 evacuated. No responsibility claim.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "ir-hormuz-offer",
        dtg: "22 SEP",
        location: "TEHRAN",
        fact: "Reuters exclusive: senior Iranian official \u2014 Iran can reopen Hormuz within seven days if US eases military pressure and lifts blockade on Iranian ports. Proposal previously passed via mediators 16 Sep.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 35.69,
        lon: 51.39,
      },
      {
        id: "ir-rezaei",
        dtg: "23 SEP",
        location: "TEHRAN",
        fact: "SNSC secretary Rezaei on state TV (Iran Intl): US given 4\u20135 days to meet Iran\u2019s conditions; until accepted, no negotiations and Hormuz will not be reopened. STATE messaging.",
        source: "STATE",
        confidence: "CLAIM",
        priority: "PRI-1",
        lat: 35.69,
        lon: 51.39,
      },
      {
        id: "ir-erbil",
        dtg: "20 SEP",
        location: "ERBIL",
        fact: "Hebrew Telegram (News_il_h): UAV near US consulate, Erbil. Same-day Greek press: drone downed near Erbil airport / coalition presence; Reuters/AFP cited on intercept. Smoke still is not a site geolocation. City pin \u2014 consulate vs airport DELTA.",
        source: "OPEN COMP",
        confidence: "CLAIM",
        priority: "PRI-2",
        lat: 36.191,
        lon: 44.009,
      },
      {
        id: "ir-6",
        dtg: "28 FEB",
        location: "HORMUZ",
        fact: "US\u2013Israel air war opens. IRGC moves to choke Hormuz. Pre-war: ~25% seaborne oil / ~20% LNG.",
        source: "OPEN COMP",
        confidence: "CONFIRMED",
        priority: "PRI-1",
        lat: 26.6,
        lon: 56.3,
      },
    ],
    markers: [
      { id: "sirik", name: "SIRIK", lat: 26.518, lon: 57.102, note: "Explosion-sounds CLAIM 6 Oct", tone: "dim" },
      { id: "hormuz", name: "HORMUZ", lat: 26.57, lon: 56.25, note: "On Peace 6 Oct; 12 hits/wk (Reuters)", tone: "hot" },
      { id: "qeshm", name: "QESHM", lat: 26.76, lon: 55.8, note: "Cargo strike 13 Sep; blast-sound reports 4/6 Oct (state media)", tone: "warn" },
      { id: "babb", name: "BANDAR ABBAS", lat: 27.18, lon: 56.27, note: "UAS / UUV claims", tone: "dim" },
      { id: "tehran", name: "TEHRAN", lat: 35.69, lon: 51.39, note: "Naqdi: strait \u201cclosed\u201d", tone: "hot" },
      { id: "erbil", name: "ERBIL", lat: 36.191, lon: 44.009, note: "UAV CLAIM 20 Sep", tone: "dim" },
      { id: "kuhestak", name: "KUHESTAK", lat: 26.802, lon: 57.026, note: "Blast-sound CLAIM 7 Oct (Fars)", tone: "dim" },
      { id: "koya", name: "KOYA", lat: 36.085, lon: 44.628, note: "Drones on KDPI camp 28 Sep", tone: "warn" },
      { id: "doha", name: "DOHA", lat: 25.286, lon: 51.526, note: "Qatar relay channel", tone: "warn" },
    ],
  };
