import type { Theater } from "./sitrep.types";

export const THEATER_ENERGY: Theater =   {
    id: "energy",
    name: "ENERGY / SEA",
    short: "SEA",
    status: "CAPE DAO / AIS LOW",
    pip: "hot",
    map: { lat: 22.4, lon: 48.2, zoom: 5 },
    kpis: [
      { label: "HORMUZ FLOW", value: "CAPE DAO HIT", tone: "hot" },
      { label: "BRENT PEAK", value: "$126", tone: "warn" },
      { label: "AIS COUNT", value: "2\u20133/DAY", tone: "hot" },
      { label: "ALT ROUTE", value: "DARK SHUTTLE", tone: "warn" },
    ],
    watch: [
      "Cape Dao Musandam attribution still open",
      "AIS commodity counts (Kpler) vs Bessent 10\u201317 mb/d claim",
      "Iran 7-day / 4\u20135-day Hormuz reopen conditions",
      "Moscow ORF / Kapotnya damage vs Russian refining",
      "Second-order: LNG, fertilizer, helium, aluminum",
    ],
    events: [
      {
        id: "en-cape-dao",
        dtg: "23 SEP",
        location: "HORMUZ / MUSANDAM",
        fact: "UKMTO + Oman MSC: CAPE DAO (Antigua/Barbuda) hit by unknown projectile ~2.5 nm off Musandam; engine-room fire; 1 crew dead, 27 evacuated. No claim of responsibility.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "en-ais-22",
        dtg: "22 SEP",
        location: "HORMUZ",
        fact: "Reuters/Kpler: commodity vessels crossing Hormuz fell to two on Monday from 10 a day earlier (AIS-visible only). Separate Marisks note: LR Stephanie and Al Maryah struck in prior incidents; responsibility unconfirmed.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "en-bessent",
        dtg: "23 SEP",
        location: "HORMUZ",
        fact: "US Treasury Secretary Bessent (Fox / Iran Intl): US forces helping move 10\u201317 million b/d through Hormuz despite tanker hits and Iran-port blockade. DELTA vs low AIS commodity counts and dark-shuttle reporting.",
        source: "STATE",
        confidence: "DELTA",
        priority: "PRI-2",
        lat: 26.57,
        lon: 56.25,
      },
            {
        id: "en-4",
        dtg: "20 SEP",
        location: "KAPOTNYA",
        fact: "UA strike on Gazprom Neft Moscow Oil Refinery (energy infra); AVT-6 / processing units hit; large fire reported.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 55.635,
        lon: 37.795,
      },
{
        id: "en-1",
        dtg: "16 SEP",
        location: "HORMUZ",
        fact: "Competing claims: US says strait kept open; press says shipping at lowest level yet.",
        source: "PRESS",
        confidence: "DELTA",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
      {
        id: "en-2",
        dtg: "21 APR",
        location: "PERSIAN GULF",
        fact: "IMO: about 20,000 mariners and 2,000 ships stranded in the Gulf at peak closure.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-2",
        lat: 27.0,
        lon: 51.0,
      },
      {
        id: "en-3",
        dtg: "20 SEP",
        location: "RIYADH",
        fact: "Red Sea shipping-protection naval meeting hosted in Riyadh after Houthi intercept.",
        source: "PRESS",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.71,
        lon: 46.68,
      },
      {
        id: "en-kkia",
        dtg: "19\u201321 SEP",
        location: "RIYADH KKIA",
        fact: "Press: Houthi strike on King Khalid Airport fuel storage / jet-fuel tanks. Telegram satellite oval is CLAIM BDA, not independent confirmation of which tanks burned.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 24.958,
        lon: 46.699,
      },
      {
        id: "en-5",
        dtg: "21 SEP",
        location: "HORMUZ",
        fact: "UKMTO 141-26: LPG tanker outbound Hormuz hit by debris from unknown projectiles. Crew safe, no environmental impact. Press split inbound vs outbound, LPG vs oil, 0 vs 2 injured.",
        source: "OPEN COMP",
        confidence: "REPORTED",
        priority: "PRI-1",
        lat: 26.57,
        lon: 56.25,
      },
    ],
    markers: [
      { id: "kapotnya-en", name: "KAPOTNYA ORF", lat: 55.635, lon: 37.795, note: "UA ORF strike", tone: "hot" },
      { id: "kkia-en", name: "KKIA FUEL", lat: 24.958, lon: 46.699, note: "Jet-fuel tanks 19\u201320 Sep", tone: "hot" },
      { id: "hormuz2", name: "HORMUZ", lat: 26.57, lon: 56.25, note: "Cape Dao hit 23 Sep", tone: "hot" },
      { id: "bab", name: "BAB EL-MANDEB", lat: 12.58, lon: 43.33, note: "Houthi / Red Sea", tone: "warn" },
      { id: "suez", name: "SUEZ", lat: 30.0, lon: 32.55, note: "Alt artery", tone: "dim" },
    ],
  };
